Adding driver for BME680
adafruit/Adafruit_Wippersnapper_Arduino pull request #262
Opened 2022-05-19 19:52 UTC by jamorris

This is the pull @brentru requested.
There's no error when uploading to the ESP32 but the Serial Monitor: "ERROR: Failed to get ambient temperature sensor reading!"

2022-05-20 15:05 UTC, brentru commented
Ok, I looked through this and got temperature working on my end. 

The primary issue is that the BME680 library doesn't use the Adafruit_Sensor library but the BME280 library does. However, we can use the BME680 test example (https://github.com/adafruit/Adafruit_BME680/blob/master/examples/bme680test/bme680test.ino) and form it into shape. The driver will look something like the MCP driver. 

I'll comment what I found in a review below.

2022-05-20 15:12 UTC, brentru requested changes
Requesting the following changes to fix and simplify the I2C_Driver_BME680. 

Let me know when you've made the requested changes so I can take another look.

2022-05-20 15:12 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +    return isInit;
Let's also add the oversampling and filter initialization here, while we're at it (see: https://github.com/adafruit/Adafruit_BME680/blob/master/examples/bme680test/bme680test.ino#L44):

```
    // Set up oversampling and filter initialization
    _bme->setTemperatureOversampling(BME680_OS_8X);
    _bme->setHumidityOversampling(BME680_OS_2X);
    _bme->setPressureOversampling(BME680_OS_4X);
    _bme->setIIRFilterSize(BME680_FILTER_SIZE_3);
    _bme->setGasHeater(320, 150); // 320*C for 150 ms
```

2022-05-20 15:12 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +  void enableSensorAmbientTemperature() {
Remove all the `enableSensor...` methods, they're handled by the I2C_Driver.h file now.

2022-05-20 15:12 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +  void disableSensorAmbientTemperature() {
Remove all the `disableSensor...` methods, they're handled by the I2C_Driver.h file now.

2022-05-20 15:12 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +  virtual void updateSensorPressure(float period) {
Remove all the `updateSensor...` methods, they're handled by the I2C_Driver.h file now.

2022-05-20 15:12 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +  bool getEventAmbientTemperature(sensors_event_t *tempEvent) {
Following how the bme680test example works (https://github.com/adafruit/Adafruit_BME680/blob/master/examples/bme680test/bme680test.ino#L52), I suggest to rewrite this method as follows:

```
  bool getEventAmbientTemperature(sensors_event_t *tempEvent) {
    // Sample the bme680's sensors
    if (! _bme->performReading())
      return false;

    // Pack the sensors_event_t's temperature field
    // with the bme680's temperature value
    tempEvent->temperature = _bme->temperature;

    return true;
  }
```

You should be able to follow this pattern with the other `getEvent...()` functions. Just pay close attention to the bme object's property name on https://github.com/adafruit/Adafruit_BME680/blob/master/examples/bme680test/bme680test.ino#L52

2022-05-20 15:12 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +  Adafruit_Sensor *_bme_temp =
You do not need the `Adafruit_Sensor` objects here since Adafruit_BME680 does not use Adafruit_Sensor.

2022-05-23 21:16 UTC, jamorris commented
@brentru I made the edits you suggested and was able to get Temperature, RH, Altitude and Pressure working. I'm still not able to get total VOC working.

2022-05-24 15:41 UTC, brentru commented
Ok, great!

For TVOC, we made a mistake. It should have been defined on the component as `gas-resistance`. 
We've since updated the validator and the component to check against the correct name:
https://github.com/adafruit/Wippersnapper_Components/blob/main/components/i2c/bme680/definition.json#L27

It isn't working because the update call `WipperSnapper_Component_I2C::update` doesn't have a block of code to handle GAS_RESISTANCE (see how it handles co2 here, as an example: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/src/components/i2c/WipperSnapper_I2C.cpp#L569). We haven't added a GAS_RESISTANCE sensor type yet to the handler component.

Would you want me to add this in, or do you want to?

2022-05-24 15:59 UTC, jamorris commented
@brentru That would be great if you could add it. Thank you.

2022-05-25 16:41 UTC, brentru commented
@jamorris  Please click the "Allow edits from maintainers" checkbox on this pull request page to allow me to add commits to it. Thanks!

2022-05-25 18:11 UTC, jamorris commented
I checked it.
![image](https://user-images.githubusercontent.com/4070721/170336569-807241b4-eff7-471e-b7d4-f8f654f9a948.png)

2022-05-25 21:15 UTC, brentru commented
@jamorris  Ok, thanks for merging and being patient. This is the first user-contribution we've had and I'm going to work on the guide to reflect our learnings so far...

The CI is failing at:
>/home/runner/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h:20:10: fatal error: Adafruit_BME680.h: No such file or directory

Could you add the string "Adafruit BME680 Library" to the library.properties file under the dependencies (here: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/library.properties#L10) and commit? 

The CI should progress after you've made that change

2022-05-27 20:26 UTC, brentru commented
Change `_gasSensorPeriod` to `gasSensorPeriod` on those lines.

2022-05-27 21:14 UTC, jamorris commented
The gas sensor is still failing to read. All other sensors work.

2022-05-31 21:39 UTC, jamorris commented
@brentru 
Serial monitor with only the gas sensor enabled:
> BME680 Initialized Successfully!
> Publishing Message: I2CResponse...Published!
> PING!
> PING!
> PING!
> PING!
> ERROR: Failed to get gas sensor reading!
> ERROR: Failed to get gas sensor reading!
> ERROR: Failed to get gas sensor reading!

Serial monitor with temperature enabled:
> PING!
> Sensor 0x77
> 	Temperature: 25.22 degrees C
> PUBLISHING -> I2C Device Sensor Event Message...PUBLISHED!

2022-06-01 14:07 UTC, brentru requested changes
Ok, one small change and the gas sensor should work. 

I tested this change locally,
```
10:06:31.669 > Packet Length:   0
10:06:33.224 > Sensor 0x77
10:06:33.225 >  Gas: 0.70 KOhms
10:06:33.225 > PUBLISHING -> I2C Device Sensor Event Message...MQTT publish packet:
```

Once you confirm it's working on your end, I'll merge in and cut a release!

2022-06-01 14:07 UTC, brentru commented on src/components/i2c/WipperSnapper_I2C.cpp
> +      if ((*iter)->getEventGas(&event)) {
This is looking for `getEventGas` but it's not named that, see below..

2022-06-01 14:07 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h
> +  bool getEventTvoc(sensors_event_t *gasEvent) {
Change this to `getEventGas`

2022-06-06 15:26 UTC, jamorris commented
I also needed to make that change to line 127 in WipperSnapper_I2C_Driver_BME680.h but I'm still seeing the "Failed to get gas sensor reading" error.

2022-06-06 15:36 UTC, brentru commented
@jamorris  Could you push your changes?

2022-10-20 16:21 UTC, brentru commented
Closing in favor of https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/355

2022-10-20 16:21 UTC, closed without merging