Add files via upload
adafruit/Adafruit_Wippersnapper_Arduino pull request #266
Opened 2022-06-02 01:58 UTC by TheGodMotherG

first attempt

2022-06-02 15:35 UTC, brentru requested changes
Requesting modifications before I test.

You also need to:
* Include the SHT4x driver in the I2C Component
  * See this recent pull request for an example: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/262/files#diff-78ec1584747f78ea74c379069a73dd165575fd5901c93829b4967d7bdebfad80
* Include handling code for the I2C Component to create the sht4x driver 
  * See this recent pull request for an example: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/262/files#diff-3dd55e689e75bcb8859a65746742c85d8b634ee427ba635ece3bd5d91711eee6
* Inclue the Adafruit SHT4x library within the library.properties file so it can be installed automatically.
  * See this recent pull request as an example: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/262/files#diff-f267f9ae2f5d5d56a1dbb305e95d40d4408d9ee7f71357f1f67fb18c29b7f082

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> + * Device driver for an SHT Humidity and Temperature sensor.
Change to: "Device drive for a SHT4x Humidity and Temperature Sensor"

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> +#include <Adafruit_Sht4x.h>
This library #include should be: "#include "Adafruit_SHT4x.h", see: https://github.com/adafruit/Adafruit_SHT4X/blob/master/examples/SHT4test/SHT4test.ino#L11

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> + * @file WipperSnapper_I2C_Driver_Sht4x.h
Change file name to `WipperSnapper_I2C_Driver_SHT4x.h`

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> +class WipperSnapper_I2C_Driver_Sht4x : public WipperSnapper_I2C_Driver {
Change class name to `WipperSnapper_I2C_Driver_SHT4x` across the file.

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> +    bool isInit = _sht->begin(_i2c, (int21_t)_sensorAddress);
sht begin() signature only needs the wire interface (see: https://github.com/adafruit/Adafruit_SHT4X/blob/master/Adafruit_SHT4x.h#L118)

Change this line to:
`bool isInit = _sht->begin(_i2c);`

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> +    return isInit;
Looking at the demo file, https://github.com/adafruit/Adafruit_SHT4X/blob/master/examples/SHT4test/SHT4test.ino#L31, you can set the precision.

Add the line:
`_sht4->setPrecision(SHT4X_HIGH_PRECISION);`

Also, you'll want to add another line below this which calls `setHeater()`, https://github.com/adafruit/Adafruit_SHT4X/blob/master/examples/SHT4test/SHT4test.ino#L47

2022-06-02 15:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_Sht4x.h
> +  void disableSensorAmbientTemperature() {
Remove this function, not required.

2022-06-03 02:56 UTC, TheGodMotherG commented
I uploaded all the requested files i named the new one SHT4x instead of sht4x and the other 2 files as well. It wont let me delete the old one but all the new files drivers and libraries are uploaded please take a look

2022-06-06 04:03 UTC, TheGodMotherG commented
I did my best to do all the recommended changes by brentru but still failed the test if anyone has any ideas how to help i would greatly appreciate it,

2022-07-15 02:51 UTC, danielfrankcom commented
It seems like `Adafruit SHT4x Library` needs to be added to the `depends` property in `library.properties`.

The build is failing with an error message that seems to indicate a missing dependency.

```
  /home/runner/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/components/i2c/drivers/WipperSnapper_I2C_Driver_SHT4x.h:20:10: fatal error: Adafruit_SHT4x.h: No such file or directory
   #include "Adafruit_SHT4x.h"
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
```

There is a list of installed libraries directly above this error message in the logs, and it doesn't include the required library that is being imported. 

`<repo root>/library.properties` contains a `depends` field with a list of dependencies. I suspect this is what the build server uses to install the required packages before running the build.

According to the Arduino IDE, there is a package named with the exact text "Adafruit SHT4x Library", so if that's added to the list of dependencies hopefully the build will pass.

![image](https://user-images.githubusercontent.com/15225573/179137463-b50f74d2-bc26-4fbf-ab41-368f13eca92b.png)

2022-08-16 17:55 UTC, brentru commented
Closing this PR in favor of https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/296 which provides tested support for SHT4x. Will be released in next version.

@TheGodMotherG  Thank you for adding the sensor definition JSON and your work here.

2022-08-16 17:55 UTC, closed without merging