Add driver for SCD40 CO2, Temperature, and Humidity Sensor
adafruit/Adafruit_Wippersnapper_Arduino pull request #286
Opened 2022-07-12 21:12 UTC by marnibrewster

This pull request adds support for using the SCD40 co2, temperature, and humidity sensor (https://www.adafruit.com/product/5187).
There is not an Adafruit library for this sensor, only a [Sensirion Arduino library](https://github.com/Sensirion/arduino-i2c-scd4x). This is already included in `library.properties`, but it does not implement `Arduino_Sensor`, so this PR likely needs some help. Also, I have never written C++ before, so I am likely botching things.
The output from doxygen that referenced my changes complained about defining variables, but I was unsure how to handle the way the Sensirion library makes one call to read (vs [the Adafruit python library that creates `scd.temperature`](https://github.com/adafruit/Adafruit_CircuitPython_SCD4X/blob/e4dba358a4e8a11c7e191c6ec8fdb143102ca91f/adafruit_scd4x.py#L122), for example).

With all of that being said, I was able to get this running locally:
![Screen Shot 2022-07-12 at 3 57 46 PM](https://user-images.githubusercontent.com/13192976/178596273-1249c860-25de-4076-9f7d-6ab5e05f8aaf.png)
![Screen Shot 2022-07-12 at 3 57 38 PM](https://user-images.githubusercontent.com/13192976/178596274-067fed21-daf8-43a2-a234-f1e17fbddef9.png)
![Screen Shot 2022-07-11 at 8 01 09 PM](https://user-images.githubusercontent.com/13192976/178596275-9883f331-709a-435c-9b57-f4c8c45b9729.png)

2022-07-12 21:13 UTC, marnibrewster commented
@brentru here is my (somewhat pathetic) attempt at the driver

2022-07-12 21:16 UTC, marnibrewster commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +  uint16_t _error;
this is what doxygen was complaining about, but I was trying to avoid NACK from calling `readMeasurement` in each method.

2022-07-15 14:59 UTC, brentru requested changes
Thank you so much for the PR, it looks great.

I have some feedback to tighten up the implementation and fix the CI errors you mentioned

2022-07-15 14:59 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> + * TEMPORARY HACK
Please add your name here :)

2022-07-15 14:59 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    _error = _scd->readMeasurement(_co2, _temperature, _humidity);
Declare `uint16 error` and the rest of the measurements in each funcn instead of as a private member below.

Also, perform the error check and handling from the example, prior to `readMeasurement()`, in each `get...()` function:
https://github.com/Sensirion/arduino-i2c-scd4x/blob/master/examples/exampleUsage/exampleUsage.ino#L109

2022-07-15 14:59 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    // check if sensor is enabled and data is available
Check if data is ready here: https://github.com/Sensirion/arduino-i2c-scd4x/blob/master/examples/exampleUsage/exampleUsage.ino#L109

2022-07-15 14:59 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +
Then, perform `readMeasurement` to update the `humidity` value: https://github.com/Sensirion/arduino-i2c-scd4x/blob/master/examples/exampleUsage/exampleUsage.ino#L119

2022-07-15 14:59 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +  uint16_t _error;
This may be resolved after you implement the changes above.

Clang is failing on our CI, please resolve using: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

2022-07-15 21:36 UTC, marnibrewster commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    // check if sensor is enabled and data is available
Thank you! This isn't in the exampleUsage.ino file in the arduino code 🤔

2022-07-15 22:37 UTC, marnibrewster commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    _error = _scd->readMeasurement(_co2, _temperature, _humidity);
Thanks for the feedback @brentru! I've pushed the requested changes.
The way you suggested is how I initially approached this, but changed it because of the errors I'm now seeing since making your change requests. Are these errors an issue? I'm assuming it's happening because [we are trying to `readMeasurement` again before the signal update interval has restarted](https://github.com/Sensirion/arduino-i2c-scd4x/blob/6b9835ea64435409ce169a29cde67cfbc2143711/src/SensirionI2CScd4x.h#L9)
This is happening before every successful reading / publish of co2, humidity, and temp:
![Screen Shot 2022-07-15 at 6 20 14 PM](https://user-images.githubusercontent.com/13192976/179320554-bd70e74a-982f-46fe-96c2-625eea358489.png)
2)?

2022-07-15 22:37 UTC, marnibrewster commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    // check if sensor is enabled and data is available
Looks like I had 3.0 installed, and 3.1 wasn't available through arduino. Installing via zip worked!

2022-07-18 16:42 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    // check if sensor is enabled and data is available
Sensirion should update it, it's an external dependency and I do not have an ETA for this vendor. I'll file an issue on their repo and update this class when it's released properly.

Could you revert back to checking error like the example in Arduino library code, sorry, https://github.com/Sensirion/arduino-i2c-scd4x/blob/5c387a1417b1742f18eab26d6579e9ffb23d4334/examples/exampleUsage/exampleUsage.ino#L68

There's also one more compiler issue popping up in CI, please fix that and we should be able to PR this in.

2022-07-19 01:37 UTC, marnibrewster commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD40.h
> +    // check if sensor is enabled and data is available
Thanks, @brentru - reverted the error logic and silenced the compiler whining 😄. It's working on my HUZZAH.

2022-07-19 14:40 UTC, brentru approved these changes
lgtm :shipit:

2022-07-19 14:40 UTC, brentru commented
@marnibrewster  Merging in and releasing, thanks for the work here!

2022-07-19 14:40 UTC, merged