adding new driver for vl53l4cd
adafruit/Adafruit_Wippersnapper_Arduino pull request #289
Opened 2022-08-02 01:30 UTC by afp316

@brentru @ladyada 
I'm a newbie so apologies if I butchered the preferred process.
I had trouble getting the sensor to initialize in WipperSnapper_I2C_Driver_VL53L4CD.h. Not sure if something weird is going on with vl53l4cd_class.h (which is the STM32 library for vl53l4cd in Arduino).
WipperSnapper_I2C.h, WipperSnapper_I2C_Driver.h, and WipperSnapper_I2C.cpp were all updated.

I'm very curious where I'm going wrong; your expertise is greatly appreciated.

2022-08-02 01:32 UTC, ladyada commented
please remove the latex folder / files

2022-08-02 01:57 UTC, afp316 commented
ok those latex folder / files should be removed.

2022-08-02 18:57 UTC, afp316 commented
@brentru The most recent PR updates the library.properties file to add in "STM32duino VL53L4CD" to the depends list.

2022-08-04 15:43 UTC, brentru requested changes

2022-08-04 15:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    _vl53l4cd = new VL53L4CD();
The constructor call within the VL53L4CD example code (https://github.com/stm32duino/VL53L4CD/blob/main/examples/VL53L4CD_Sat_HelloWorld/VL53L4CD_Sat_HelloWorld.ino#L70) requires two parameters:

`VL53L4CD sensor_vl53l4cd_sat(&DEV_I2C, A1);`
(also referenced in the class here - https://github.com/stm32duino/VL53L4CD/blob/main/src/vl53l4cd_class.h#L57)


The first parameter is "pin 6 (XSHUT) of the VL53L4CD satellite connected to pin A1 of the Nucleo board". 

We do not currently have a way to pass in an extra pin when using I2C devices with WipperSnapper. This sensor is not yet compatible with WipperSnapper until we have a method of passing a pin to an I2C component. I haven't yet seen this, so it has to be added.

2022-08-04 20:26 UTC, ladyada commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    _vl53l4cd = new VL53L4CD();
you can probably pass in -1

2022-08-04 21:41 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    _vl53l4cd = new VL53L4CD();
If that's the case, I'll continue w/review!

2022-08-04 21:44 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    bool isInit = _vl53l4cd->begin((uint8_t)_sensorAddress, _i2c);
This functionality does not exist within the vl53l4cd class.

Instead, you may want to add the rest of the calls within the `setup()` function from https://github.com/stm32duino/VL53L4CD/blob/main/examples/VL53L4CD_Sat_HelloWorld/VL53L4CD_Sat_HelloWorld.ino#L86 into this function.

2022-08-04 21:47 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +  bool getEventProximity(sensors_event_t *proximityEvent) {
First, check for new data like in: 
https://github.com/stm32duino/VL53L4CD/blob/main/examples/VL53L4CD_Sat_HelloWorld/VL53L4CD_Sat_HelloWorld.ino#L110
If new data isn't ready, immedately `return false;`

Then, clear the HW interrupt like in:
https://github.com/stm32duino/VL53L4CD/blob/main/examples/VL53L4CD_Sat_HelloWorld/VL53L4CD_Sat_HelloWorld.ino#L119

Finally, read the measured distance like in:
https://github.com/stm32duino/VL53L4CD/blob/main/examples/VL53L4CD_Sat_HelloWorld/VL53L4CD_Sat_HelloWorld.ino#L122

2022-08-04 21:48 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    proximityEvent->proximity = _vl53l4cd->VL53L4CD_StartRanging();
Instead of `proximityEvent->proximity` (which does not yet exist within Adafruit IO's sensor definitions, try:

`proximityEvent->data[0] = results.distance_mm;`

2022-08-04 21:49 UTC, brentru commented on src/components/i2c/WipperSnapper_I2C.cpp
> +        WS_DEBUG_PRINT(event.proximity);
event.data[0]

2022-08-04 21:49 UTC, brentru commented on src/components/i2c/WipperSnapper_I2C.cpp
> +            &msgi2cResponse, event.proximity,
`event.data[0]` here, too

2022-08-04 22:32 UTC, afp316 commented
Dang you're good.  I'm a bit embarrassed.  Thanks for being patient with me.

2022-08-05 15:03 UTC, brentru commented
@afp316 The driver looks much better and compiles, thanks for the work! Next, please format it using clang-format (we have a guide on this here: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format) as its failing the clang-format test step (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/runs/7684301606?check_suite_focus=true). 

You will also need to run doxygen across your code as well, we have a guide explaining how to do this here: https://learn.adafruit.com/the-well-automated-arduino-library/doxygen

2022-08-05 15:05 UTC, brentru requested changes

2022-08-05 15:05 UTC, brentru commented on src/components/i2c/WipperSnapper_I2C.cpp
> +        WS_DEBUG_PRINTLN(" mm");
Could you remove this line? We define proximity in Adafruit IO as:

`Distance from an object to a sensor, non-unit-specific`

2022-08-08 15:28 UTC, brentru requested changes
This PR needs to be linted using clang before I can merge it in. There is a link to an Adafruit guide on this further up.

2022-08-08 15:28 UTC, brentru commented on README.md
> +# Adafruit IO - WipperSnapper Beta [![Build Status](https://travis-ci.com/afp316/Adafruit_TSL2561.svg?branch=master)](https://travis-ci.com/afp316/Adafruit_TSL2561)
I do not know why this got changed, please drop this commit.

2022-11-11 18:41 UTC, brentru commented
@afp316 Are you still interested in working on this issue?

2022-11-13 13:19 UTC, afp316 commented
Hey Brent.  I kind of lost track on this one, I probably won't be
finishing.

On Fri, Nov 11, 2022, 13:41 Brent Rubell ***@***.***> wrote:

> @afp316 <https://github.com/afp316> Are you still interested in working
> on this issue?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/289#issuecomment-1312062196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXAAGVULBRDG7VYMLP7WWSLWH2HO5ANCNFSM55JM3TXQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-14 16:22 UTC, brentru commented
Ok - no problem!

2022-11-14 16:22 UTC, closed without merging