Add STEMMA Soil Sensor support
adafruit/Adafruit_Wippersnapper_Arduino pull request #303
Opened 2022-08-24 17:56 UTC by marcuswu

Add Adafruit STEMMA Soil Sensor support.

Note that I went a different direction with my project, directly using Arduino code rather than using WipperSnapper. The project is installed in a hard to reach place so I haven't had a chance to test this against the hardware I have yet.

2022-08-24 21:28 UTC, brentru requested changes
@marcuswu  Hi - thank you for this pull request. It's a shining example! I have a few changes to request.

Also - I do have a stemma soil sensor. Would you like me to test this for you tomorrow?

2022-08-24 21:28 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +            msgDeviceInitReq->i2c_device_properties[propertyIdx].sensor_period);
Please add `break;` under L141 otherwise the switch will drop through

2022-08-24 21:28 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +  long _RawSensorPeriod =
Could you change the case to `_rawSensorPeriod` and `_rawSensorPeriodPrv`?

2022-08-24 21:28 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_STEMMA_Soil_Sensor.h
> + * Copyright (c) Marcus Wu 2022 for Adafruit Industries.
Please remove "for Adafruit Industries"

2022-08-24 22:04 UTC, marcuswu commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +            msgDeviceInitReq->i2c_device_properties[propertyIdx].sensor_period);
OMG, I know better than this :)

2022-08-24 22:05 UTC, marcuswu commented
> @marcuswu Hi - thank you for this pull request. It's a shining example! I have a few changes to request.
> 
> Also - I do have a stemma soil sensor. Would you like me to test this for you tomorrow?

I was going to pull my project down to test this over the weekend, but if you have one sitting around, that would be awesome!

2022-08-30 18:44 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_STEMMA_Soil_Sensor.h
> +    if (_rawSensorPeriod != 0) {
@marcuswu I just tested this on hardware. This comparison causes the function to return `false` - please check if the period is equal to 0 here, instead.

2022-08-31 02:24 UTC, marcuswu commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_STEMMA_Soil_Sensor.h
> +    if (_rawSensorPeriod != 0) {
Sorry, I probably won't get to this until Thursday. I've got some long days in leadership meetings at work.

2022-08-31 16:00 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_STEMMA_Soil_Sensor.h
> +    if (_rawSensorPeriod != 0) {
No problem - ping me whenever you're set!

2022-09-01 19:23 UTC, marcuswu commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_STEMMA_Soil_Sensor.h
> +    if (_rawSensorPeriod != 0) {
I had copied that check from another sensor and it didn't make sense here. I dug into the Adafruit_seesaw code and found that it returns 65535 when there's a read error and used that for error checking.

Unfortunately, I'm now getting errors in the pipeline that I don't know how my changes are causing. Does it look like instability in the pipeline itself?

2022-09-02 14:36 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_STEMMA_Soil_Sensor.h
> +    if (_rawSensorPeriod != 0) {
It was an issue with our CI Pipeline, I kicked it. Seems to have resolved and passed.

2022-09-02 14:38 UTC, brentru commented
@marcuswu  This is all set and ready to merge.

Could you bump the library version to .46 here:
https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/library.properties#L2

and here:
https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/src/Wippersnapper.h#L63

I'll merge in once committed.

2022-09-02 14:38 UTC, brentru approved these changes

2022-09-06 15:14 UTC, brentru approved these changes

2022-09-06 15:28 UTC, merged