Add vl53l0x driver - finish work by Afp316 #291
adafruit/Adafruit_Wippersnapper_Arduino pull request #363
Opened 2022-11-12 17:33 UTC by tyeth

This just finishes off the fine work by @afp316 in #291 
Rebased off of latest main, amended last commit to remove .pio/.vscode changes, ran clang-format.

2022-11-14 16:27 UTC, brentru commented
Build failing due to https://github.com/adafruit/Adafruit_MQTT_Library/issues/217

2022-11-15 16:09 UTC, tyeth commented
Not sure how to retrigger workflow, but just read about hash sign-off so here goes: 
#sign-off

2022-11-15 16:14 UTC, brentru commented
I'm not familiar with #sign-off...

On the workflow, https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/3451873666 you should be able to re-run jobs?

![Add_vl53l0x_driver_-_finish_work_by_Afp316__291_·_adafruit_Adafruit_Wippersnapper_Arduino_b23b0ff](https://user-images.githubusercontent.com/322428/201970050-534d69ef-d732-46db-8929-22a35f5e75b0.png)

2022-11-15 19:25 UTC, tyeth commented
Sadly not available, I think there's a repository or Org setting for allowing workflow runs from pull requests / forks. This was related https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories

2022-11-15 20:56 UTC, brentru commented
`-Wmissing-field-initializers` is a warning being treated (correctly) as an error with the ESP32 compiler. Please open an issue over on the Adafruit vl53l0x repo and tag me and I'll (or an engineer from adafruit) will fix it.

2022-11-16 17:18 UTC, brentru commented
It did pass, but the build warnings were still thrown: https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/3473545620/jobs/5805679630#step:8:73

I'm not sure why at the moment..

> Also how should it be fixed, does the .h file that defines the struct get defaults specified, or does on define only on each initialisation

When a struct is initialized, [it must contain all members within the brace-enclosed list of initializers](https://en.cppreference.com/w/c/language/struct_initialization)

* https://github.com/adafruit/Adafruit_VL53L0X/blob/master/src/vl53l0x_def.h#L220

> Is it ever okay to just disable that warning for a line like that initialisation?

Not if we can fix it :)

2022-11-20 01:41 UTC, tyeth commented
So there was a missing bit in wippersnapper related to the setting of the time of last poll for the proximity sensor type. 

Now just another initialisation warning that I'll stick up an issue for or fix eventually. 
Not really happy with the reliability of the sensor in default config so I've selected high accuracy, but may experiment with other libraries too. The Dev flag in components with the banners is great :)

2022-11-21 17:17 UTC, brentru requested changes
@tyeth Read over the PR, some comments..

2022-11-21 17:17 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +      @brief    Disables the device's object light sensor, if it exists.
object light sensor -> proximity sensor

2022-11-21 17:17 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L0X.h
> + * Copyright (c) Brent Rubell 2022 for Adafruit Industries.
add your name instead of mine here please, along with the original PR's author

2022-11-21 17:17 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L0X.h
> +    Serial.println("VL53L0X begin()");
We typically don't have WS_DEBUG calls within sensor drivers - do you need one here?

2022-11-21 17:17 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L0X.h
> +#ifdef WS_DEBUG
What is going on in this #ifdef?

2022-11-21 18:17 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L0X.h
> +#ifdef WS_DEBUG
ah so this is turning on the driver debug if ws_debug was true. happy to remove

2022-11-21 18:22 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +      @brief    Disables the device's object light sensor, if it exists.
Doh, I spotted that and didn't change it at the time, kept on with the polling stuff, then forgot - naughty boy

2022-11-21 18:54 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L0X.h
> +#ifdef WS_DEBUG
Remove please! Serial.println should also be removed

2022-11-28 17:31 UTC, brentru commented
@tyeth  - OK, addressed in https://github.com/adafruit/Adafruit_VL53L0X/pull/59 and released in https://github.com/adafruit/Adafruit_VL53L0X/releases/tag/1.2.1. Arduino Lib manager will pick this up (probably later today) and I will re-kick the CI.

Thanks for being patient.

2022-11-30 22:47 UTC, brentru commented
@tyeth This is failing clang/doxy (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/3517128928/jobs/6038336339). Should be ready to go after. Thanks for your patience. I've also fixed the flaky behavior for building the ESP32-Sx platforms via the CI.

2022-12-01 15:21 UTC, tyeth commented
Wow green lights across the board, a more rare and pleasant sight that we might like to admit 📉 
Congratulations on the CI work🥇 Just done the doxygen fix so that should be it!

2022-12-01 15:31 UTC, afp316 commented
Nice job and thank you both for your hard work and patience.
I couldn't figure out the Clang and doxygen stuff.

On Thu, Dec 1, 2022 at 10:21 AM Tyeth Gundry ***@***.***>
wrote:

> Wow green lights across the board, a more rare and pleasant sight that we
> might like to admit 📉
> Congratulations on the CI work🥇 Just done the doxygen fix so that should
> be it!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/363#issuecomment-1333930137>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXAAGVQNQKJ2EICXDJYOQF3WLC7AVANCNFSM6AAAAAAR6NF2JQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-01 16:13 UTC, brentru approved these changes

2022-12-01 16:13 UTC, brentru commented
Great work - thank you both. Will be included in next release.

2022-12-01 16:13 UTC, merged