Add SSID scan and validation
adafruit/Adafruit_Wippersnapper_Arduino pull request #377
Opened 2022-11-29 20:27 UTC by brentru

Resolves https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/328 by adding a function to perform a WiFi scan and check if the user-defined SSID within secrets.json is within the list of scanned SSIDs.

2022-11-29 21:36 UTC, makermelissa requested changes
Looks mostly good. I made some comments, but it looks like a lot of similar code. Would having the code in a base class function and then maybe checking an overridable variable to see if the class has been loaded make it easier to maintain?

2022-11-29 21:36 UTC, makermelissa commented on src/network_interfaces/Wippersnapper_ESP8266.h
> +    }
Same thing here.

2022-11-30 20:46 UTC, brentru commented
@makermelissa 

> Would having the code in a base class function and then maybe checking an overridable variable to see if the class has been loaded make it easier to maintain?

I'm not sure because each network interface includes its own board-specific implementation/API of the WiFi class

2022-11-30 20:50 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    }
It would! Implemented in next commit.

2022-11-30 21:16 UTC, makermelissa commented
> @makermelissa
> 
> > Would having the code in a base class function and then maybe checking an overridable variable to see if the class has been loaded make it easier to maintain?
> 
> I'm not sure because each network interface includes its own board-specific implementation/API of the WiFi class

Fair enough.

2022-11-30 21:17 UTC, makermelissa approved these changes
Looks good. Thanks.

2022-11-30 22:42 UTC, merged