Add Sonoff TH10/16
adafruit/Adafruit_Wippersnapper_Arduino pull request #476
Opened 2023-08-28 14:00 UTC by tyeth

This adds the initial provisional ALPHA quality release for the Sonoff TH10/16 Relays, using the ESP8266.

2023-08-28 15:47 UTC, tyeth commented
Will require the board adding to the CI system, both in this repo (doxy yaml), and ci-arduino 
https://github.com/adafruit/ci-arduino/blob/master/build_platform.py#L54-L179
(Currently the ci-arduino repo used is not the adafruit copy, but the brentru fork)

2023-09-06 22:39 UTC, brentru requested changes
Looks OK, some questions and changes. Have you gotten this running yet?

2023-09-06 22:39 UTC, brentru commented on platformio.ini
> +board_build.filesystem = littlefs
I am curious - why is this flag required for the sonoff_th but not for the huzzah ESP8266?

2023-09-06 22:39 UTC, brentru commented on src/Wippersnapper_Boards.h
> +#define STATUS_LED_PIN 13 // pull down
Is this pin pulled down by default?

2023-09-06 22:39 UTC, brentru commented on src/components/digitalIO/Wippersnapper_DigitalGPIO.cpp
> +#if defined(ARDUINO_ESP8266_ADAFRUIT_HUZZAH) || defined(ESP8266_SONOFF_TH)
This applies to every ifdef like this, would we want to detect the ESP8266 arch instead of individual boards? Both boards we're using here (and elsewhere) seem to take the same pinout/pd resistor

2023-09-07 12:42 UTC, tyeth commented on platformio.ini
> +board_build.filesystem = littlefs
I think maybe it is required for both. I couldn't push the filesystem image for the ESP8266 huzzah without this, I kept forgetting as it was part of my stash with secrets data file. Maybe I've got something configured wrong, but I think it was defaulting to spiffs rather than littlefs. I did the initial sonoff work just before the huzzah arrived later in the day and I was then able to get the secrets across and see debug with both sonoff + huzzah.
 I'll try to check on a fresh machine at some point soon.

2024-09-24 16:12 UTC, closed without merging