Add LTR390 sensor with switching mode example
adafruit/Adafruit_Wippersnapper_Arduino pull request #499
Opened 2023-10-03 14:36 UTC by tyeth

@brentru was thinking something like this for the switching light modes between Ambient Light (ALS) and UV (UVS) modes, inside  each event type.

2023-10-03 21:39 UTC, brentru requested changes

2023-10-03 21:39 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      @brief    Reads the LTR390's UV value into an event.
Do we have a unit for UV-value or is it unitless?

2023-10-03 21:39 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +    _ltr390->setMode(LTR390_MODE_ALS);
Which mode, UV or ALS, would a person use more often? We should make that the "default" mode here.

2023-10-03 21:39 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      delay(100);
Do we need this delay?

2023-10-03 21:39 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      delay(100);
Do we need this delay?

2023-10-04 10:18 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      delay(100);
I think the delay needs to be >105, maybe 110 for safety? This is assuming the 18bit resolution giving 100ms integration time
![image](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/assets/6692083/37e7deda-a281-4194-8077-9674d86cda6d)
And the switch from standby (which makes sense to implement if you agree) to reading takes 5ms before starting reading (or checking the measurement scheduler)
![image](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/assets/6692083/931e0ced-099a-483c-a215-146c8e1b6a52)
https://optoelectronics.liteon.com/upload/download/DS86-2015-0004/LTR-390UV_Final_%20DS_V1%201.pdf

2023-10-04 10:32 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +    _ltr390->setMode(LTR390_MODE_ALS);
Maybe it's a UV sensor by title so we pick that 🤷 no idea really, but it also claims lux output for ambient which seemed useful and relevant to more projects maybe

2023-10-04 10:32 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      @brief    Reads the LTR390's UV value into an event.
seems to be a unitless count, which can be converted to an index too
![image](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/assets/6692083/5ce721c1-1e71-43ca-aec6-7a1ccb508378)

2023-10-04 15:53 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      @brief    Reads the LTR390's UV value into an event.
okay, lets leave it then

2023-10-04 16:08 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +    _ltr390->setMode(LTR390_MODE_ALS);
Let's set it to `LTR390_MODE_UVS` within the init. as that's what happens first in the example sketch and may be the largest use case.

2023-10-04 16:09 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      delay(100);
I don't want to implement a blocking loop since we're technically already polling this in a loop. We could increase the delay to 110ms (5ms for the conversion + safety)

2023-10-04 16:09 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      delay(100);
See above ^

2023-10-04 16:09 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_LTR390.h
> +      delay(100);
Change to 110ms

2023-10-05 20:06 UTC, tyeth commented
@brentru that should be okay now. I've still not enabled standby mode between reads. Currently it feels like power usage is less important than having readings readily sampled, but maybe once we cover deep-sleep on esp32 we can revisit such thoughts

2023-10-05 20:46 UTC, brentru approved these changes
Changes look good, thanks for working this through with me

2023-10-05 20:46 UTC, merged