Initial tweaking of previous poll period
adafruit/Adafruit_Wippersnapper_Arduino pull request #512
Opened 2023-11-24 16:46 UTC by tyeth

2023-11-24 17:58 UTC, tyeth commented
@brentru tested on S2 TFT with LTR390, period set at 5mins, immediate data sent.

2023-11-27 14:34 UTC, brentru commented on src/components/digitalIO/Wippersnapper_DigitalGPIO.cpp
> +    long curtime = millis() - 1;
`curTime`

2023-11-27 14:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +  long SENSOR_STARTING_PERIOD_PRV =
1) Where did this formula come from?
2) Caps and case - `sensorStartingPeriodPrv`

2023-11-27 14:36 UTC, brentru commented on src/components/digitalIO/Wippersnapper_DigitalGPIO.cpp
> +    long curtime = millis() - 1;
Do we want this to be a `long`, millis() returns an `unsigned long`

2023-11-27 14:37 UTC, brentru requested changes
This addresses a big issue, thank you! Requesting clarification and changes

2023-11-27 15:13 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver.h
> +  long SENSOR_STARTING_PERIOD_PRV =
Thinking yes swap to a macro. The formula was 24hrs in milliseconds, to account for the unknown period (max of 24hrs in wippersnapper)

2024-03-22 15:16 UTC, merged