Initial VL6180X implementation
adafruit/Adafruit_Wippersnapper_Arduino pull request #528
Opened 2024-01-08 12:18 UTC by tyeth

This add the STM VL6180X, returning range and light level / lux at Gain level 5.

Plan is to revisit this component and others with customisable parameters once we have I2C custom sensor parameters supported in WipperSnapper components

2024-01-11 21:38 UTC, brentru requested changes
@tyeth  Two things..

2024-01-11 21:38 UTC, brentru commented on src/Wippersnapper.h
> +#define WS_DEBUG          ///< Define to enable debugging to serial terminal
@tyeth  why are these being added back?

2024-01-11 21:38 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL6180X.h
> +    proximityEvent->data[0] = range;
What units does this return - do we have a type for it?

2024-01-11 21:51 UTC, tyeth commented on library.properties
> -url=https://github.com/adafruit/Adafruit_IO_Arduino
@brentru This needs updating so I slipped it in with this PR

2024-01-11 21:52 UTC, tyeth commented on src/Wippersnapper.h
> +#define WS_DEBUG          ///< Define to enable debugging to serial terminal
I've moved these higher, above line 64, so that WS_DEBUG_PRINT is available to the i2c drivers for better debugging.

2024-01-11 21:53 UTC, brentru commented on library.properties
> -url=https://github.com/adafruit/Adafruit_IO_Arduino
Yeah I caught that one, thanks for adding it.

2024-01-11 21:54 UTC, brentru commented on src/Wippersnapper.h
> +#define WS_DEBUG          ///< Define to enable debugging to serial terminal
Okay!

2024-01-11 21:58 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL6180X.h
> +    proximityEvent->data[0] = range;
I believe millimetres for all proximity sensors, but selecting the proximity sensor / subcomponent type we have a unitless display in IO, labelled Value with the title SENSORNAME: Proximity Sensor. 
Sadly the proximity values don't agree between sensors so I'm almost thinking leave it as unitless "Value"

2024-01-12 15:22 UTC, brentru commented
@tyeth  Approved, please resolve the merge conflicts then OK to merge in

2024-01-12 15:23 UTC, brentru approved these changes

2024-01-12 15:48 UTC, merged