Add titano
adafruit/Adafruit_Wippersnapper_Arduino pull request #538
Opened 2024-01-16 14:44 UTC by tyeth

Drafting this to check build before review

2024-01-17 15:14 UTC, tyeth commented
As I've reverted the branch of ci-arduino change, I thought there needs to be a merge of https://github.com/adafruit/ci-arduino/pull/177 however the build has completed regardless.

2024-01-17 15:28 UTC, brentru requested changes
One question/comment

2024-01-17 15:28 UTC, brentru commented on src/components/analogIO/Wippersnapper_AnalogIO.cpp
> +      _analog_input_pins[i].prvPeriod = 0L;
Can we do this in a separate PR?

2024-01-17 16:06 UTC, brentru approved these changes
Approved, LGTM

2024-01-17 16:43 UTC, tyeth commented
May not be ready for prime time, or at least I can't get my titano to boot correctly (red light of doom)

2024-01-29 15:09 UTC, tyeth commented
This will be included/superseded by #540

2024-01-29 15:09 UTC, closed without merging