BUILD CHECK - DONT MERGE - Fs reinit plus titano
adafruit/Adafruit_Wippersnapper_Arduino pull request #540
Opened 2024-01-17 19:18 UTC by tyeth

2024-01-26 21:31 UTC, brentru requested changes

2024-01-26 21:31 UTC, brentru commented on src/Wippersnapper.cpp
> +  delay(500);
Is this wait/attach/wait pattern required here?

2024-01-26 21:31 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +    fsHalt("ERROR: Failure initializing LittleFS!");
Remove the `while(1)...` beneath L32 as the program will never reach it after `fsHalt()` is called

2024-01-26 21:31 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +void WipperSnapper_LittleFS::fsHalt(String msg) {
Could you doxygen this function, including the new `String msg` argument?

2024-01-26 21:31 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +    WS_DEBUG_PRINTLN("ERROR: Halted execution!");
Maybe "Fatal Error: {error msg}" instead?

2024-01-26 21:31 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.h
> +  void fsHalt(String msg = "");
Instead of providing a default argument of `""` here, we should _require_ anything calling `fsHalt()` to include the message.

2024-01-26 21:31 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
>      delay(1000);
Do we need this delay?

2024-01-26 21:31 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
>      statusLEDSolid(WS_LED_STATUS_FS_WRITE);
Does this LED function need to get set within the loop? Can we do it outside it?

2024-01-26 21:31 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
>      while (1)
Remove L101 `while(1)` as execution wont reach this point

2024-01-26 21:31 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
> +    fsHalt("New filesystem created! Please RESET your board.");
* Press the reset button on your board

2024-01-26 21:31 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
> +bool Wippersnapper_FS::initFilesystem(bool force_format) {
Please document `force_format` in the comment

2024-01-26 21:31 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
>      // statusLEDSolid(WS_LED_STATUS_FS_WRITE);
Maybe we remove this line and the delay if the LED isn't turned on? and L414 is commented out? 

Would we want the LED on to signal to a user?

2024-01-29 11:41 UTC, tyeth commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
>      delay(1000);
Don't want to flood the serial, my pc doesn't like that, could be less. I debated this morning changing the LED to flash, even adding a parameter for the number of flashes (each cycle flips the LED until counter reached [reset] then skip next flash [wait 3sec] then repeat). We could then have nice error translation just from the number of flashes of a red LED. [neopixel probably shows enough already]

2024-01-29 11:50 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
>      // statusLEDSolid(WS_LED_STATUS_FS_WRITE);
I've now made it consistent with the LittleFS version, LED on solid for now indicating the user should check serial / files, with serial message repeated every second.

2024-01-29 14:59 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
>      delay(1000);
Why don't we print only once then, outside the loop, but flash indefinitely

2024-01-29 15:11 UTC, tyeth commented on src/Wippersnapper.cpp
> +  delay(500);
No, good shout, the filesystem should already be flushed

2024-01-29 15:16 UTC, tyeth commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
>      delay(1000);
Due to missing the serial message, which is common when the user is not expecting a problem and only connects serial after the error has been printed.

2024-01-30 19:07 UTC, brentru commented
Tested on FunHouse (secrets file persisted between reboots)

@tyeth  could you bump the library version and then merge+release?

2024-01-30 19:07 UTC, brentru approved these changes

2024-01-30 21:30 UTC, merged