Add VL53L1X
adafruit/Adafruit_Wippersnapper_Arduino pull request #548
Opened 2024-02-08 20:21 UTC by tyeth

Untested, ending for the day possibly, and wanted a couple of UF2's for testing next

2024-02-08 20:29 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    if (!_VL53L1X->dataReady()) {
I half wanted to add a delay / retry here, like try 3 times (potentially need 500ms integration time) then return NaN, hiding that logic in here felt a bit wrong even though I've done it once before. Instead I'm following the fail=false for dataready so it will infinitely retry. Maybe adding a delay makes sense, but probably at the retry loop instead of each driver. Just adding this comment so you're aware @brentru

2024-02-08 20:30 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    if (!_VL53L1X->dataReady()) {
What does the example driver do?

2024-02-08 21:14 UTC, tyeth commented
Ignoring the build size, this is now ready for review @brentru

2024-02-08 21:15 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    if (!_VL53L1X->dataReady()) {
nothing, just loops again, but there is a delay for visual clarity in the loop.

2024-02-15 18:31 UTC, brentru commented
Holding until https://github.com/adafruit/arduino-esp32/issues/18 is merged and tested. This PR will increase the available application flash and resolve the funhouse build error.

2024-02-16 13:08 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    if (!_VL53L1X->dataReady()) {
Add retry logic

2024-03-22 15:26 UTC, brentru requested changes
@tyeth  Requesting changes across this PR

2024-03-22 15:26 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    uint8_t attempts = 0;
Remove the retry loop, bail out and `return false` if no data is ready.

2024-03-22 15:26 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    if (proximityMM <= 0 || proximityMM > 4000) {
The [example](https://github.com/adafruit/Adafruit_VL53L1X/blob/main/examples/VL53L1X_simpletest/VL53L1X_simpletest.ino#L49) checks against a value of `-1.

Where are you getting this check from:
`if (proximityMM <= 0 || proximityMM > 4000)`?

2024-03-22 15:26 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L1X.h
> +    _VL53L1X->clearInterrupt();
I am not sure if we need to call `clearInterrupt()` here. [On the example](https://github.com/adafruit/Adafruit_VL53L1X/blob/main/examples/VL53L1X_simpletest/VL53L1X_simpletest.ino#L49), an invalid read value of `-1` `return`s from the `loop()` before the interrupt is cleared.

2024-03-22 15:27 UTC, brentru commented
@tyeth  Why is funhouse failing? Is this PR simply using the old workflow and can't be updated until we merge?

2024-03-22 16:21 UTC, brentru approved these changes

2024-03-22 16:21 UTC, merged