WIP: Add VL53L4CD
adafruit/Adafruit_Wippersnapper_Arduino pull request #550
Opened 2024-02-12 17:55 UTC by tyeth

2024-04-05 11:38 UTC, tyeth commented on platformio.ini
The debug changes should probably be reverted - pretty sure esp-builtin wont work for plain esp32 chips (maybe with esp-usb-bridge project / coprocessor)

2024-04-10 15:41 UTC, tyeth commented
@brentru ready for review please

2024-04-10 20:43 UTC, brentru requested changes
@tyeth  Requesting the following changes

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +  const char *getVL53L4CDStatusDescription(int statusCode) {
I'd drop this in favor of printing the `int` like in https://github.com/stm32duino/VL53L4CD/blob/main/examples/VL53L4CD_Sat_HelloWorld/VL53L4CD_Sat_HelloWorld.ino#L124 especially as these are all strings.

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +  const char *getVL53L4CDStatusDescription(int statusCode) {
After this is done, maybe we should implement this in the STM32Duino driver and PR into the `stm32duino/VL53L4CD` library.

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_WARNING_SIGMA_THRESHOLD                                \
See my comment below about the `getVL53L4CDStatusDescription` function and the driver. We can remove this define because it's not referenced outside of `getVL53L4CDStatusDescription`

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_WARNING_SIGNAL_LOW                                     \
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_DISTANCE_LOW                                     \
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_PHASE_OUT_OF_LIMIT 4 ///< Phase out of valid limit
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_HARDWARE_FAIL 5      ///< Hardware failure
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_WARNING_NO_WRAP_CHECK                                  \
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_WRAP_TARGET                                      \
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_PROCESSING_FAIL 8 ///< Processing failure
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_CROSSTALK_FAIL 9  ///< Crosstalk signal failure
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_INTERRUPT 10      ///< Interrupt error
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_MERGED_TARGET 11  ///< Merged target detected
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_SIGNAL_TOO_LOW                                   \
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_ERROR_OTHER 255 ///< Other error (e.g., boot error)
same here

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +#define VL53L4CD_STATUS_VALID 0 ///< Returned distance is valid
Globally define this at the top of the file.

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +     * _VL53L4CD->VL53L4CD_Off();
I don't understand the purpose of this comment block, is the following code emulating these function calls?

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    } else {
unnecessary as it's hardcoded

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    uint16_t sigmaThreshold = -1;
Don't need to declare a `uint` here, you can pass it to the `VL53L4CD_GetSigmaThreshold` func. directly

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    uint16_t signalThreshold = -1;
Don't need to declare a `uint` here, pass to the function in the following line.

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +      WS_DEBUG_PRINTLN(100);
Can drop the `else`

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    }
can drop the `else`

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +    for (uint8_t i = 0;
Is this a retry-loop? Can you rename `i` to something descriptive like `retries`?

2024-04-10 20:43 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +      // TODO: Once I2C sensors fire all data points during a single call, we
Did you end up implementing this `TODO`? Did you want to make a `NOTE` instead for the future?

2024-04-19 00:20 UTC, tyeth commented
@brentru if you wouldn't mind re-reviewing this one

2024-04-19 14:34 UTC, brentru requested changes
Conditionally approving this and requesting one minor change. Merge in when you've added it.

2024-04-19 14:34 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CD.h
> +        if (results.range_status != VL53L4CD_STATUS_VALID) {
Please check against `0` here since `VL53L4CD_STATUS_VALID` is only referenced once in this file

2024-04-19 15:09 UTC, merged