Fix: MAX17048 - Return NaN if no battery attached
adafruit/Adafruit_Wippersnapper_Arduino pull request #557
Opened 2024-03-19 12:38 UTC by tyeth

This checks the version + ID before each read, returning NaN if not valid (no battery attached).

2024-03-19 12:38 UTC, tyeth reviewed
Tagging @brentru for review

2024-03-19 12:47 UTC, tyeth commented
Not sure whats gone on with the build there, errors suggest some bracket isn't closed or idf changed or something is fubar.
Will look when I get back later

2024-03-19 13:55 UTC, brentru commented
@tyeth  Run clang locally over `src/components/i2c/drivers/WipperSnapper_I2C_Driver_MAX17048.h`

2024-03-19 14:00 UTC, brentru requested changes

2024-03-19 14:00 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_MAX17048.h
> +    if (chipID == 0x00 || chipID == 0xFF)
Can you #define these numbers?

2024-03-19 14:00 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_MAX17048.h
> +    if (chipVersion == 0x0000 || chipVersion == 0xFFFF)
Same here - can you check if they are present within the MAX library's header, and reference the macros or define them?

2024-03-22 16:35 UTC, tyeth commented
There are no longer changes required as the library has been augmented with returning NaNs, and the begin will fall if no battery attached (same check inside lib).

2024-03-22 16:35 UTC, closed without merging