Refactored commit - VL53L4CX default settings
adafruit/Adafruit_Wippersnapper_Arduino pull request #564
Opened 2024-04-09 16:51 UTC by tyeth

2024-04-10 15:42 UTC, tyeth commented
@brentru ready for review, release blocked until partition size resolved on some build targets as discussed yesterday

2024-04-25 18:40 UTC, tyeth commented
@brentru ready for review, tested locally, will retest on staging before merge

2024-04-26 16:15 UTC, brentru requested changes

2024-04-26 16:15 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> + * Copyright (c) 2022 Tyeth Gundry for Adafruit Industries
Could you change the copyright date?

2024-04-26 16:15 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +    _VL53L4CX = new VL53L4CX(_i2c, -1);
Consider defining the magic `-1` param here as a macro.

2024-04-26 16:15 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +      WS_DEBUG_PRINTLN("Failed to set VL53L4CX distance mode to long!");
Should this failure return an error (`false`)?

2024-04-26 16:15 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +      for (currentObject = 0; currentObject < no_of_object_found;
I am curious if this could be encapsulated in a private function instead of a large conditional loop?

2024-04-26 16:15 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +      WS_DEBUG_PRINT(" .");
Would it be possible to refactor this into a private function, for clarity?

2024-05-17 16:59 UTC, tyeth commented
Re-ready for review @brentru

2024-05-17 17:55 UTC, brentru requested changes

2024-05-17 17:55 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +    for (uint8_t retries = 0;
Could we return NAN, and return immediately vs retrying three times? These drivers are supposed to be very small and fast, like an interrupt routine.

2024-05-17 17:55 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +  bool getProximity(sensors_event_t *proximityEvent, int index = 0) {
I feel this function is doing many things and it's resulting in a conditional statement that's difficult for me to parse. Could we refactor this a bit? 

I'll suggest some ideas below..

2024-05-17 17:55 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +      if (no_of_object_found - 1 < index) {
This index boundary is confusing. Could you either reformat it, or refactor it out into a function that is then checked?

2024-05-17 17:55 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +      bool retVal = updateDataPointIfValid(pMultiRangingData->RangeData[index],
I'm unsure how you'd want to restructure the conditional, but this (L150-L152) is hidden within the nested if statement. It's the code's desired outcome, so, could we make it more visible?

2024-05-17 19:02 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +  bool getProximity(sensors_event_t *proximityEvent, int index = 0) {
Yeah it's not exactly friendly and easily readable, will have a rethink

2024-06-12 16:24 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +      { USBSerial.println(status); };
?

2024-06-12 16:35 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +    for (uint8_t retries = 0;
NaN doesn't mean data not ready, especially with these ToF sensors. It's meant to mean nothing in range (but a clear signal response).

I kind of feel like we should return false and retry in the next polling loop, but the retry logic in main polling loop is not smart (endlessly retries sensors returning false). 
Maybe I should I rejig the polling logic in the main file to retry falses a couple of times instead (per poll period) before marking their next poll period in the future regardless (like a good read would after first value returned)?

2024-06-14 17:15 UTC, brentru approved these changes
@tyeth  Conditionally approving! There is one small change I requested, once that change is made, feel free to merge in!

2024-06-14 17:15 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_VL53L4CX.h
> +    if (_VL53L4CX->VL53L4CX_SetMeasurementTimingBudgetMicroSeconds(200000) !=
Can you make `200000` a macro?

2024-06-25 16:07 UTC, merged