Add MCP9601 with K-Type Thermocouple
adafruit/Adafruit_Wippersnapper_Arduino pull request #565
Opened 2024-04-09 17:21 UTC by tyeth

2024-04-10 20:46 UTC, brentru requested changes
LGTM, once you test merge when ready

2024-04-10 20:46 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_MCP9601.h
> + * Copyright (c) Brent Rubell 2022 for Adafruit Industries.
Add your name and current year here

2024-04-10 20:47 UTC, brentru approved these changes

2024-10-08 17:09 UTC, tyeth commented
This is not planned for support, due to failing to initialise after being i2c scanned. Hotplugging the device after scanning was deemed unacceptable. Maybe revisit after python version of wippersnapper lands

2024-10-08 17:09 UTC, closed without merging