Add NAU7802
adafruit/Adafruit_Wippersnapper_Arduino pull request #577
Opened 2024-04-24 20:30 UTC by tyeth

2024-04-25 18:42 UTC, tyeth commented
Appreciate some initial feedback @brentru 
Not to be merged before I test on staging (I'll merge)

2024-04-26 16:21 UTC, brentru requested changes

2024-04-26 16:21 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_NAU7802.h
> +    }
Are these are all failure states that should `return false` if chip communication fails? Would you want to refactor this out into a `bool configure_nau7802()` function that returns based on if configuration fails or succeeds?

2024-04-26 16:21 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_NAU7802.h
> +      if (millis() - start > 1000) {
Could you change this timeout from `1000ms` to `250ms`, and make it a macro?

2024-04-26 16:21 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_NAU7802.h
> +        WS_DEBUG_PRINTLN("NAU7802 not available");
Potentially change the warning to reflect the docstring, "Whether there is new ADC data to read", rather than saying the sensor is not available.

2024-04-26 16:21 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_NAU7802.h
> +    rawEvent->data[0] = (float)_nau7802->read();
Would we want to support a raw force value in Adafruit_Sensor?

2024-05-17 16:46 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_NAU7802.h
> +    rawEvent->data[0] = (float)_nau7802->read();
Thinking for now not to, but as Limor was talking about adding the HX711 soon (another load cell / wheatstone bridge sensor) we may wish to revisit that decision. I have added to an existing issue on the Adafruit_Sensor repo for this, with comments/thoughts, so that we can continue the discussion.

https://github.com/adafruit/Adafruit_Sensor/issues/39

2024-05-17 19:01 UTC, tyeth commented
@brentru forgot this ones also re-ready for review

2024-05-17 19:13 UTC, brentru approved these changes
approving conditionally for the one change (refactoring something out)

2024-05-17 19:13 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_NAU7802.h
> +    // Take 10 readings to flush out old readings (10 samples per second)
Please refactor into a `flush_nau` function or similar

2024-05-23 14:34 UTC, merged