Pb error msgs
adafruit/Adafruit_Wippersnapper_Arduino pull request #584
Opened 2024-05-08 17:02 UTC by tyeth

Adds extra logging on encoding errors for protobuf/nanopb.

2024-05-17 17:06 UTC, tyeth commented
Feedback welcomed, just threw this together for that PyPortal Titano user.

2024-05-17 17:42 UTC, brentru commented
@tyeth  Have you tested this on physical HW yet and played around with it?

2024-05-17 17:44 UTC, tyeth commented
Mainly just ran a few sensors and components on a board or two, didn't see
anything not working

On Fri, 17 May 2024, 18:42 Brent Rubell, ***@***.***> wrote:

> @tyeth <https://github.com/tyeth> Have you tested this on physical HW yet
> and played around with it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/584#issuecomment-2118104046>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABTBZ4ZYEU4ET2CGUU2YOCDZCY6Q5AVCNFSM6AAAAABHNK565KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJYGEYDIMBUGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-17 18:10 UTC, brentru approved these changes

2024-05-23 15:31 UTC, tyeth commented
Skipping this release (beta83), will be reviewed in context (PyPortal Titano) next week, then make it into 84.

2024-07-01 11:22 UTC, tyeth commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +          lastResult, // return variable (unused here)
**not** `(unused here)`

2024-07-01 13:57 UTC, tyeth commented
@brentru ready for re-review

2024-07-01 15:03 UTC, brentru requested changes
@tyeth Overall, this PR is great. It addresses issues when the PB encoder/decoder doesn't work as we expect, airlift-specific issues.

However, it still needs some tweaking before I want to merge. Could you review the following feedback and either comment so we can have a convo about it, or add commits to address them? Thanks!

2024-07-01 15:03 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    sscanf(currentVersion.c_str(), "%d.%d.%d", &curMajor, &curMinor, &curPatch);
Add handling for if `sscanf` returns an error

2024-07-01 15:03 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    sscanf(requiredVersion.c_str(), "%d.%d.%d", &reqMajor, &reqMinor,
Add handling for if `sscanf` returns an error

2024-07-01 15:03 UTC, brentru commented on src/network_interfaces/Wippersnapper_WIFININA.h
> +/*!
Same readability issue as Wippersnapper.h

2024-07-02 14:22 UTC, tyeth commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +  bool compareVersions(const String &currentVersion,
switched back to const char*, been retested on pyportal titano

2024-07-03 00:46 UTC, tyeth commented
@brentru ready for re-review, I've dealt with the formatting issue + feedback, retested on pyportal titano.
 Found the RSSI virtual issue. I'd left a breadcrumb of info in another commit message, easily found after walking away from the problem, I just needed to call the method getRSSI unqualified (without WS.) when inside Wippersnapper.cpp/base-class.
 Lastly I was trying to print the RSSI before connect when no longer storing it, so refactored to print in the check_valid_ssid network interface methods instead (where the scan happens and we can briefly get access to all RSSIs before connecting).

2024-07-19 15:47 UTC, tyeth commented
Tagging @brentru as ready for re-review

2024-07-19 17:48 UTC, brentru requested changes

2024-07-19 17:48 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +  const char *_fv;             /*!< nina-fw firmware version. */
You changed `_fv` from a String (dynamically managed) to a `const char`. I'm not seeing where `_fv` ptr is properly initialized to a value i.e: `const char* _fv = "1.0.0"`

2024-07-19 17:48 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +          20000, // timeout interval (ms)
Make these magic numbers macros

2024-07-19 17:48 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +          200);  // interval between retries
Make this a macro

2024-07-19 17:48 UTC, brentru commented on src/Wippersnapper.h
> +#define RETRY_FUNCTION_UNTIL_TIMEOUT(func, result_type, result_var, condition, \
Does this handle negative values?

2024-07-25 20:30 UTC, tyeth commented
@brentru ready for review
Cleaned up the feedback, added the pico cert for staging and wifi101 ignores for esp32 / 8266, and improved the wifi network logging (mentions which SSID it's just connected to).

2024-07-25 20:45 UTC, brentru approved these changes
LGTM! This is a **lot** of changes, do you want to cut a new release for it?

2024-07-25 20:55 UTC, tyeth commented
That's a very good idea. Easier roll back that way, but should be fine ☺️

2024-07-25 20:57 UTC, merged