Add main I2C sensor Retry-loop
adafruit/Adafruit_Wippersnapper_Arduino pull request #593
Opened 2024-06-12 22:14 UTC by tyeth

This is a result of having retries in the drivers/wrappers, and a desire for them to be faster (more interrupt like). We are therefore removing unnecessary delays while waiting to retry one sensor multiple times, and instead retrying the entire suite of sensors up to three times before failing that periodic reading event.

I was trying to add another driver with a long retry time, and this work was the result instead. See #564

There will be a follow up PR to remove any unnecessary retries during I2C sensor data reads once this is merged.

2024-07-01 13:56 UTC, tyeth commented
@brentru ready for review

2024-07-01 15:15 UTC, brentru requested changes
I think this is good! It increases how robust the `update()` loop is. 

I have two notes:

Performance: I know you noted it in the PR description, but I want to get to it in this PR. Let's mark failed reads and only retry the sensors that fail.

Code complexity: I think the `update()` loop is growing in its complexity and provided an idea below about encapsulation

2024-07-12 15:58 UTC, tyeth commented on src/components/i2c/WipperSnapper_I2C.cpp
> +  int retries = 3;
ah yeah good spot, I removed the repetitive setting failure bool from each sensor type branch and added to the end check for no events which created the bug.
Now I have refactored to use `sensorEventRead` which will correctly skip retrying if already sent in a previous loop iteration (time based check), updating the prvPollPeriod on success, and update the bool on failures. That should mean the loop will run once assuming no failures, and each sensor will only be read once (+n failures).

2024-07-12 16:03 UTC, tyeth commented on src/components/i2c/WipperSnapper_I2C.cpp
> +      // AMBIENT_TEMPERATURE sensor (°C)
@brentru Now implemented, please have a look. Also see comment above for explanation of the situation.
One last thing is I didn't return a bool, as it needs to be cumulative so I'm passing instead. I guess I could refactor to have the bool response and sensorsReturnedFalse = sensorsReturnedFalse | sensorEventRead(lots of args) on every call

2024-07-15 14:31 UTC, brentru commented on src/components/i2c/WipperSnapper_I2C.cpp
> +  int retries = 3;
Perfect!

2024-07-15 16:49 UTC, tyeth commented on src/components/i2c/WipperSnapper_I2C.cpp
> +      // AMBIENT_TEMPERATURE sensor (°C)
Currently each call is passing the bool in like here [https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/593/files/e06c29ab2a29c99eccc2e2ab4347797c3ffaba31..62bd535185f1a1c27cff6db54e4a53ffe697e27d?diff=split&w=0#diff-3dd55e689e75bcb8859a65746742c85d8b634ee427ba635ece3bd5d91711eee6R1025](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/593/files/e06c29ab2a29c99eccc2e2ab4347797c3ffaba31..62bd535185f1a1c27cff6db54e4a53ffe697e27d?diff=split&w=0#diff-3dd55e689e75bcb8859a65746742c85d8b634ee427ba635ece3bd5d91711eee6R1025)

leading to getting updated here

[https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/593/files/e06c29ab2a29c99eccc2e2ab4347797c3ffaba31..62bd535185f1a1c27cff6db54e4a53ffe697e27d?diff=split&w=0#diff-3dd55e689e75bcb8859a65746742c85d8b634ee427ba635ece3bd5d91711eee6R1333](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/593/files/e06c29ab2a29c99eccc2e2ab4347797c3ffaba31..62bd535185f1a1c27cff6db54e4a53ffe697e27d?diff=split&w=0#diff-3dd55e689e75bcb8859a65746742c85d8b634ee427ba635ece3bd5d91711eee6R1333)

2024-07-16 13:46 UTC, brentru commented on src/components/i2c/WipperSnapper_I2C.cpp
> +      // AMBIENT_TEMPERATURE sensor (°C)
I think it's OK as-is

2024-07-16 13:46 UTC, brentru approved these changes

2024-07-16 21:45 UTC, merged