Wifi multi network support for esp32/esp8266/PicoW
adafruit/Adafruit_Wippersnapper_Arduino pull request #601
Opened 2024-07-09 15:22 UTC by tyeth

This adds a new field called `alternative_networks' to the network_type_wifi object in the secrets.json settings file.

It's an array of objects (with fields network_ssid and network_password). 

There is a maximum size of 3, although larger arrays will be tolerated **only the first 3 entries will be used**.

Example config:
```json
{
  "io_username": "tyeth_demo",
  "io_key": "my_super_secret_adafruit_io_key",
  "network_type_wifi": {
    "network_ssid": "free4all",
    "network_password": "password",
    "alternative_networks": [
      {
        "network_ssid": "free4all_2G",
        "network_password": "password"
      },
      {
        "network_ssid": "HOTSPOT",
        "network_password": "password"
      },
      {
        "network_ssid": "Tenda_60C06C",
        "network_password": "password"
      },
      {
        "network_ssid": "THERMAL",
        "network_password": "password"
      }
    ]
  },
  "status_pixel_brightness": 0.2
}
```

2024-07-10 19:58 UTC, tyeth commented on src/Wippersnapper.cpp
> -    delayMicroseconds(1000);
This now matches the #ifndef esp8266 delay(1000)

2024-07-10 20:06 UTC, tyeth commented on src/network_interfaces/ws_networking_pico.h
> +    // WiFi.persistent(false);
retest pico reconnecting

2024-07-10 20:08 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
> +    fsHalt(String("ERROR: Unable to parse secrets.json file - "
clean up this autoformatted madness

2024-07-10 20:11 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
> +        "are invalid, please "
cleanup autoformatting madness

2024-07-10 20:12 UTC, tyeth reviewed
cleanup autoformatting and retest pico reconnecting between phone then home wifi

2024-07-10 20:12 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS.cpp
> +                  "deserializeJson() failed with code") +
cleanup autoformat madness

2024-07-12 20:09 UTC, brentru requested changes
Overall this is a very solid feature implementation and I'll test it out on Monday. I've left comments requesting clarity and modifications.

Resolves https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/376

2024-07-12 20:09 UTC, brentru commented on src/network_interfaces/Wippersnapper_ESP8266.h
> +          if (strlen(WS._multiNetworks[i].ssid) > 0 &&
See my comment about this in ESP32.h

2024-07-12 20:09 UTC, brentru commented on src/network_interfaces/Wippersnapper_ESP8266.h
> +        if (_wifiMulti.run(5000) == WL_CONNECTED) {
Why are we calling `_wifiMulti.run(5000)` and checking `WL_CONNECTED` here and on L266? Is there a difference between the two? Why would we connect/run twice?

2024-07-12 20:09 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +      int8_t networkCount = networks.size();
in c++, `.size` returns a `size_t`. You could cast a `size_t` to an `int8_t` here though

2024-07-12 20:09 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +      int8_t networkCount = networks.size();
change `networkCount` to `altNetworkCount` for clarity

2024-07-12 20:09 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +            "ERROR: No networks found in network_type_wifi in secrets.json!");
Wouldn't this be searching within the `alternative_networks` array not the `network_type_wifi` array?

2024-07-12 20:09 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +      // check if over 5, warn user and take first five
3, not 5

2024-07-12 20:09 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +        if (i >= 3) {
I'm somewhat against warning them and adding more strings to compile vs educating them via guides/docs.

2024-07-18 12:21 UTC, tyeth commented on src/Wippersnapper.cpp
> -    delayMicroseconds(1000);
To match the line just obscured in preview [1second delay](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/628e0892d1a5e95be74dbe29713189f679ba4331/src/Wippersnapper.cpp#L2478)

2024-07-18 12:32 UTC, tyeth commented on src/network_interfaces/Wippersnapper_ESP32.h
> +      else if (strcmp(_ssid, WiFi.SSID(i).c_str()) == 0)
The normal network ssid doesn't get added to the altNetworks, so this check needs to still happen.
It has just occurred to me that I failed to test one eventuality that the primary ssid could connect when none of the altNetworks were found (which would fail). I always had some alt networks in range.

I should move this to be a separate check, dropping the else, probably above the multi-network/altNetworks check as that will be the less common path.

2024-07-18 12:34 UTC, tyeth commented on src/network_interfaces/Wippersnapper_ESP32.h
> +      WiFi.setAutoReconnect(false);
On the ESP32 the device gets locked to the first connected SSID and will always attempt to reconnect to it in multi-network mode, unless autoReconnect is set false. 
I only realised this by doing debug logging on the basic arduino multi wifi test and playing with the options, noticing it wouldn't rescan and join another network when I switched off one (and debug logged that it was repeatedly trying to reconnect to the old network).

2024-07-19 15:38 UTC, tyeth commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +        if (i >= 3) {
Yeah I'm torn on that, I don't realistically believe people read the docs before trying something. Happy to remove, but not really a fan of silent truncation, maybe a shorter fatal error string rather than listing unused networks and continuing.

2024-07-19 15:42 UTC, tyeth reviewed
@brentru this should be good to go now. All feedback resolved except the "unused networks" error message, but left some not marked resolved so you see the explanations. 
Let me know what you think

2024-07-19 17:50 UTC, brentru approved these changes

2024-07-19 17:50 UTC, brentru commented on src/network_interfaces/Wippersnapper_ESP8266.h
> +    // _wifiMulti
Why is this commented out? Remove for clarity if unused

2024-07-19 17:50 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +        if (i >= 3) {
Error is OK for now, we'll want to move to a new error reporting system maybe in API v2

2024-07-23 18:09 UTC, merged