Add DS2484 hosting DS18b20 temp sensor
adafruit/Adafruit_Wippersnapper_Arduino pull request #603
Opened 2024-07-18 16:38 UTC by tyeth

2024-07-18 17:33 UTC, tyeth commented
and a disconnected device from the start:
![image](https://github.com/user-attachments/assets/28c66cfb-6866-4f33-af16-a2577e4e2934)

2024-07-22 15:49 UTC, tyeth commented
@brentru this is ready for review

2024-07-22 19:03 UTC, brentru requested changes
@tyeth  Looks good overall! Requesting some clarification/changes.

2024-07-22 19:03 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_DS2484.h
> +    for (int i = 0; i < 9; i++) {
You are enumerating over `data`. While a fixed number (9), you still want to make the iteration account for data[] being a dynamic array type. Change the evaluation in the iterator to something like `i < sizeof(data)/sizeof(data[0])` instead of fixing it at `9`.

2024-07-23 19:15 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_DS2484.h
> +    for (int i = 0; i < 9; i++) {
Nice thought, done

2024-07-23 19:36 UTC, tyeth commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_DS2484.h
> +    _ds2484->OneWireReset();
Good catch

2024-07-23 19:43 UTC, tyeth commented
@brentru should be good to go

2024-07-23 20:44 UTC, brentru approved these changes
LGTM!

2024-07-23 20:44 UTC, merged