598 preprocessor script for printing the library versions to boot outtxt
adafruit/Adafruit_Wippersnapper_Arduino pull request #607
Opened 2024-07-29 21:17 UTC by tyeth

2024-08-20 17:06 UTC, brentru commented
@tyeth  Is this ready for review?

2024-10-10 17:28 UTC, tyeth commented
This **should not be merged** until the ci-wippersnapper branch for ci-arduino has been updated, as part of  https://github.com/adafruit/ci-arduino/pull/196, and this PR had the refs updated in the build script. 
I probably need to resolve the conflict with the build file anyway.
Alternatively the current (598-blah) ref will work as it's ci-wippersnapper + print dependencies changes.

2024-10-10 17:28 UTC, tyeth commented
@brentru this should be ready for review

2024-10-10 19:40 UTC, brentru requested changes
@tyeth  Thanks for taking this on, its a simple approach. I do have some q's

2024-10-10 19:40 UTC, brentru commented on .github/workflows/build-clang-doxy.yml
> +          repository: tyeth/ci-arduino
Would we need to modify the ci-arduino `wippersnapper` branch to match this `ref`?

2024-10-10 19:40 UTC, brentru commented on .github/workflows/build-clang-doxy.yml
> +    name: 🏗️ESP32-Sx DEV BUILDS
Are we only doing this for Sx builds or all builds?

2024-10-10 19:40 UTC, brentru commented on .github/workflows/build-clang-doxy.yml
> +        run: python3 ci/build_platform.py ${{ matrix.arduino-platform }} --build_timeout 48000 --include_print_dependencies_header ./src/print_dependencies.h
Should we do this on all platforms, or just ESP32-x?

2024-10-10 19:40 UTC, brentru commented on src/print_dependencies.cpp
> +const char *project_dependencies = R"(
How does this work? As I understand from reading thru everything, it populates `project_dependencies` with a list of dependencies by using `arduino-cli lib list` during pre-compilation. Or is this during compilation?

2024-10-10 19:40 UTC, brentru commented on src/provisioning/littlefs/WipperSnapper_LittleFS.cpp
> +  WS_DEBUG_PRINTLN(project_dependencies);
Nice, really simple way to print out the ptr to the list

2024-10-15 18:57 UTC, merged