Add Adafruit Feather ESP32-C6
adafruit/Adafruit_Wippersnapper_Arduino pull request #615
Opened 2024-08-13 12:46 UTC by tyeth

2024-08-13 16:17 UTC, brentru commented
@tyeth  The CI is encountering a failure for the c6, https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/10371737786/job/28712750874?pr=615

2024-08-13 16:20 UTC, tyeth commented
Yep, needs the boards PR merged to pickup the offset from the boards json

2024-08-13 17:47 UTC, brentru requested changes

2024-08-13 17:47 UTC, brentru commented on platformio.ini
> +; Espressif ESP32-C6 4MB NO PSRAM esp32-c6-devkitm-1
Do we need this? Are you hoping to add the c6 devkit?

2024-08-14 10:33 UTC, tyeth commented on platformio.ini
> +; Espressif ESP32-C6 4MB NO PSRAM esp32-c6-devkitm-1
I've been adding and using the Espressif devkit versions just for debugging, only the S3 and this C6 so far, but long term the plan was to add them as supported boards.
 It felt like doing all the Adafruit boards first was best, and I think it was mentioned in a meeting to do the LoLin and a couple of other boards next, then the esp devkits. Think that was based on popularity.
I've had a quick search of basecamp, but can't see anything Lolin / new boards list related, it must have been a discussion in our weekly meeting before the summer.

2024-08-14 14:09 UTC, brentru commented on platformio.ini
> +; Espressif ESP32-C6 4MB NO PSRAM esp32-c6-devkitm-1
Okay!

2024-08-14 14:09 UTC, brentru approved these changes
@tyeth LGTM

2024-08-20 20:22 UTC, merged