Add retry if data not ready for SCD30
adafruit/Adafruit_Wippersnapper_Arduino pull request #632
Opened 2024-09-19 15:06 UTC by tyeth

2024-09-19 15:10 UTC, tyeth reviewed
@brentru ready for review.
This fixes #627

2024-09-23 14:35 UTC, brentru requested changes
@tyeth  I agree with the overall structure, I do have some comments and questions about the types your using and how they're being packed.

2024-09-23 14:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD30.h
> +    if (!_scd->dataReady()) {
This segment is difficult to read. Could you refactor the logic out into to a new function?

2024-09-23 14:35 UTC, brentru commented on src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD30.h
> +    tempEvent->temperature = _temperature;
I think it's confusing to mix types like this (`_temperature` is a `float`, `tempEvent` is a `sensors_event_t`). 

Instead, could we have:
*  `_temperature`, `_humidity` and `_co2` declared as protected `sensors_event_t` types?
* You could also remove the need for the (`sensors_event_t tempEvent;` and `sensors_event_t humidEvent;`) decls. on L77:L78. 
* You could then remove the (now redundant) reassignments in L79:L81, too.

2024-09-24 18:11 UTC, brentru approved these changes
This reads much better now, thanks for making adjustments.

2024-09-24 18:30 UTC, merged