Use_analogReadMilliVolts-for-esp32-scaledAnalogRead-false
adafruit/Adafruit_Wippersnapper_Arduino pull request #635
Opened 2024-09-27 17:55 UTC by tyeth

2024-10-15 18:58 UTC, tyeth commented
@brentru this is ready for review

2024-10-15 20:13 UTC, brentru requested changes

2024-10-15 20:13 UTC, brentru commented on src/components/analogIO/Wippersnapper_AnalogIO.cpp
> +                                          long periodOffset) {
Do we ever pass `periodOffset` in? When this func. is called on L531, it doesn't seem to include periodOffset.

When would we include `periodOffset` and why?

2024-10-15 20:13 UTC, brentru commented on src/components/analogIO/Wippersnapper_AnalogIO.cpp
> +        // All boards ADC values scaled to 16bit, in future we may need to
Could you refactor this into a `CalculateHysteresis` function and call that function here?

2024-10-15 20:36 UTC, tyeth commented on src/components/analogIO/Wippersnapper_AnalogIO.cpp
> +                                          long periodOffset) {
I reuse the function / logic check for the on change delay, passing in 500, on line 381 https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/635/files#diff-4e111e8f7d844aa38d092958262d5b77683072105409145224c36ab513c0109cR381

2024-11-15 15:14 UTC, tyeth commented
@brentru this should be ready again, retested it after the refactor

2024-11-15 17:22 UTC, merged