DRAFT CI Assets - Initial sorting of scanned wifi networks
adafruit/Adafruit_Wippersnapper_Arduino pull request #661
Opened 2024-11-13 18:26 UTC by tyeth

2024-11-14 20:51 UTC, tyeth commented
Works on Pico, which is what I was after as it was affecting my testing of other things.

```
---- Reopened serial port COM40 ----
Found single wifi network in secrets.json
Adafruit.io WipperSnapper
-------Device Information-------
Firmware Version: 1.0.0-beta.92
Board ID: rpi-pico-w
Adafruit.io User: tyeth
WiFi Network: free4all_2G
MAC Address: 28:CD:C1:0E:17:E8
-------------------------------
Generating device's MQTT topics...
Running Network FSM...
Establishing network connection...
Performing a WiFi scan for SSID...ERROR: Your requested WiFi network was not found!
WipperSnapper found these WiFi networks: 
free4all -50dB
free4all -52dB
free4all -55dB
Tenda_60C06C -79dB
free4all -82dB
ERROR [WDT RESET]: ERROR: Unable to find WiFi network, rebooting soon...
ERROR [WDT RESET]: ERROR: Unable to find WiFi network, rebooting soon...
```

2024-11-15 15:17 UTC, tyeth commented
@brentru this is ready for review

2024-11-15 16:39 UTC, brentru requested changes
@tyeth  I have a few review notes below and also some questions:

1) Do we take the network with the highest RSSI?
2) If we fail to connect to the defined network, do we try again with the next network in our list of networks?
3) What is the purpose of sorting by RSSI if we are not going to take the network with the largest RSSI or if its not defined?

2024-11-15 16:39 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    int rssi;      /*!< Received Signal Strength Indicator */
RSSI should be type `int32_t` to [match the WiFi library](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiScan.h#L50)

2024-11-15 16:39 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    std::vector<WiFiNetwork> networks(n);
I am not sure about using a vector/dynamic alloc. here, allowing too many possible networks will increase sort time.

Instead, could you define a global `MAX_WIFI_NETWORK` macro of 15 possible network options?

2024-11-15 16:39 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    char ssid[33]; /*!< SSID (Max 32 characters + null terminator */
Looks like `SSID` is a string in the WiFi library, so we should match the type
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiScan.h#L48

2024-11-15 16:39 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +      networks[i].ssid[sizeof(networks[i].ssid) - 1] =
If you switch SSID to a String type, it will be null-terminated during compilation.

2024-11-15 16:39 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +#include <algorithm>
Do we want this here, or moved to be included by WipperSnapper.h or another file (networking.h?) so it's included by all the drivers?

2024-11-15 16:39 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    for (const auto &network : networks) {
Why are we using `auto`type assignment here? Instead of this overhead, we could iterate until the end of the array

2024-11-26 21:41 UTC, tyeth commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    char ssid[33]; /*!< SSID (Max 32 characters + null terminator */
as part of the purge of dynamic allocation, this will not be stored as a string, also only applies to esp32, the remaining platforms are const char* returned from WiFi.SSID(int)

2024-11-26 21:41 UTC, tyeth commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    std::vector<WiFiNetwork> networks(n);
Agreed, resolved.

2024-11-26 21:42 UTC, tyeth commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +      networks[i].ssid[sizeof(networks[i].ssid) - 1] =
to keep the allocation not dynamic we'll skip string for these structs

2024-11-27 02:05 UTC, tyeth commented
Log of wifi multi connection attempt on ESP8266 with Wifi debug logging on (can't generate for WS firmware due to dbg size)
```
02:03:40.042 -> state: 2 -> 3 (0)
02:03:40.042 -> state: 3 -> 5 (10)
02:03:40.042 -> add 0
02:03:40.042 -> aid 8
02:03:40.042 -> cnt 
02:03:40.042 -> 
02:03:40.042 -> connected with free4all, channel 8
02:03:40.042 -> dhcp client start...
02:03:40.042 -> wifi evt: 0
02:03:42.073 -> ip:192.168.50.226,mask:255.255.255.0,gw:192.168.50.1
02:03:42.073 -> wifi evt: 3
02:03:42.141 -> [WIFIM] Connected:
02:03:42.141 -> [WIFIM]   SSID: free4all
02:03:42.141 -> [WIFIM]   IP:   192.168.50.226
02:03:42.141 -> [WIFIM]   MAC:  82:7F:54:A1:5B:41
02:03:42.141 -> [WIFIM]   CH:   8
02:03:42.141 -> [WIFIM]   RSSI: -71
02:03:42.141 -> WiFi connected: free4all 192.168.50.226
02:03:43.119 -> WiFi connected: free4all 192.168.50.226
02:03:44.136 -> WiFi connected: free4all 192.168.50.226
02:03:45.147 -> WiFi connected: free4all 192.168.50.226
02:03:46.141 -> WiFi connected: free4all 192.168.50.226
02:03:47.149 -> WiFi connected: free4all 192.168.50.226
02:03:48.123 -> WiFi connected: free4all 192.168.50.226
```

2024-11-29 15:27 UTC, brentru requested changes

2024-11-29 15:27 UTC, brentru commented on src/Wippersnapper.h
>  #define WS_MAX_ALT_WIFI_NETWORKS 3 ///< Maximum number of alternative networks
Should this be moved into `https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/src/Wippersnapper_Networking.h` instead, since it'd get #define'd before the network iface?

2024-11-29 15:27 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +  bool static compareByRSSI(const WiFiNetwork &a, const WiFiNetwork &b) {
Instead of passing a ptr to a `WiFiNetwork` object, pass the `rssi` values directly into this function from the caller

2024-11-29 15:27 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
>      for (int i = 0; i < n; ++i) {
I would advise against using the if/else to catch the case where there are too many networks. If you want to truncate on `WS_MAX_SORTED_NETWORKS,` add that to the for() loop's conditional.

2024-11-29 15:27 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +        numSavedNetworks++;
Change to: `++numSavedNetworks`

2024-11-29 15:27 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    std::sort(networks, networks + numSavedNetworks, compareByRSSI);
If `compareByRSSI` is doing a direct comparison, you could use the `<` comparison from this method rather than create a new one. It might be cleaner not to refactor that one out.

2024-12-11 02:08 UTC, tyeth commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    std::sort(networks, networks + numSavedNetworks, compareByRSSI);
@brentru Would you mind spelling that out for me? Do you mean there's a way to pass the RSSI ints from the network structs directly to the potentially refactored CompareByRSSI, and if so then there's a way to do the simple < here and then need no comparator method?
Alternatively do you mean just chuck a lamda doing the direct access to the network structs and comparing the rssi elements here instead of having the compare method, like
```
std::sort(networks, networks + numSavedNetworks, [](const WiFiNetwork &a, const WiFiNetwork &b) {
    return a.rssi > b.rssi;
});
```

2024-12-11 16:26 UTC, brentru commented on src/network_interfaces/Wippersnapper_AIRLIFT.h
> +    std::sort(networks, networks + numSavedNetworks, compareByRSSI);
I'm no longer sure, so you may want to just keep this as-is for now.

2024-12-20 18:48 UTC, brentru approved these changes

2024-12-20 18:48 UTC, brentru commented
@tyeth  LGTM, merge when tests are passing

2024-12-21 02:43 UTC, merged