RP2040 WDT=8.3secs - enable after wifi connect
adafruit/Adafruit_Wippersnapper_Arduino pull request #670
Opened 2024-12-17 22:16 UTC by tyeth

Split out from wifi sorting pr, needed ideally (works without but wifi multi times out at 8seconds) before release of firmware version for #664

2024-12-19 16:36 UTC, brentru requested changes
Small feedback, looks good. Please ping me when addressed.

2024-12-19 16:36 UTC, brentru commented on platformio.ini
> +    -DDEBUG_RP2040_PORT=Serial
Comment out debugging flags using `;`

2024-12-19 16:36 UTC, brentru commented on src/Wippersnapper.cpp
>    WS.enableWDT(WS_WDT_TIMEOUT);
Consider moving this guard into the `enableWDT()` call, so we aren't `ifndef''ing each time we call `enableWDT()`

2024-12-19 16:36 UTC, brentru commented on src/Wippersnapper.h
> +#define WS_WDT_TIMEOUT 8388 ///< Pico Max WDT timeout
Verbiage Change: `Pico` -> `RP2040` since Pico is the board not the chip which has this issue, and the newer Pico2 or future Picos may solve it.

2024-12-20 18:09 UTC, tyeth commented on platformio.ini
> +    -DDEBUG_RP2040_PORT=Serial
I'm keeping this one as a debug output build so the flag can remain

2024-12-20 18:49 UTC, tyeth commented
@brentru this one too please (switched enableWDT to after wifi connect)

2024-12-20 18:54 UTC, brentru approved these changes
@tyeth  LGTM

2024-12-21 02:43 UTC, merged