USB Reattach fixes + Specify reset time remaining + secrets != 0xFF
adafruit/Adafruit_Wippersnapper_Arduino pull request #672
Opened 2024-12-17 22:48 UTC by tyeth

This is desired with the pico2w release (with #664 ) to improve user first run experience

2024-12-19 16:42 UTC, brentru requested changes
This addresses the TinyUSB reattach issue we've been seeing and I like the count-up WDT feed function.

One small comment for code clarity:

2024-12-19 16:42 UTC, brentru commented on src/Wippersnapper.cpp
> +  for (int i = 0;; i++) {
This is a really clever count-up system to dynamically feed the wdt!

Before the loop, I would like to see these magic numbers defined as const ints: `25`, `20, `5000`, to help future maintainers read through this code

2024-12-20 18:52 UTC, tyeth commented
@brentru this one updates haltError to use an optional time argument, and parameterises the timeouts

2024-12-20 18:56 UTC, brentru approved these changes
Much cleaner! LGTM!

2024-12-21 02:43 UTC, merged