Review PR: Add "Offline" SDLogger Mode
adafruit/Adafruit_Wippersnapper_Arduino pull request #676
Opened 2024-12-27 16:38 UTC by brentru

This pull request is not meant to be merged in. It is a review-only pull request for specific regions of code.

### Codebase regions for review
* Added a new class, `ws_sdcard` - for interfacing with a micro SD Card breakout.
  * Request: please take a careful look at how `parseConfigFile` functions and looks
  * Request: please take a careful look at how we switch between production and debug-mode in this class
  * `BuildJSONDoc` and `LogJSONDoc` API interfaces are present for each type of component
  * This class also supports a Real-Time-Clock breakout.
* API calls for interacting with `ws_sdcard` and mode-switching (determining whether the device is online or offline) within `WipperSnapper_V2` class in two functions -`provision()` and `connect()` 
* Added API calls for parsing the SD CS pins from the JSON file on the WIPPER drive within classes - `FS_V2` and `LittleFS_V2` 
* Refactored `network_interfaces/` to `adapters/` to allow for a WipperSnapper device without a network interface (`offline/`).
  * Added new class, `adapters/offline/ws_offline_pico` to support a Raspberry Pi in offline mode.

### Workflow enhancements for review:
* Added a new GitHub Actions workflow file, `run-tests.yml`, to automate testing using Wokwi.

2025-01-09 18:05 UTC, tyeth commented on tests/diagrams/offline.json
> +        "attrs": { "color": "green" }
Should we be using bounce:0 here too? (Like ../diagram.json)

2025-01-09 18:05 UTC, tyeth commented on examples/Wippersnapper_demo/Wippersnapper_demo.ino
> +  while (!Serial) delay(10);
Think this should be commented out again

2025-01-09 18:05 UTC, tyeth commented on examples/Wippersnapper_demo/Wippersnapper_demo.ino
> +  //wipper.run();
Think this should be re-enabled

2025-01-09 18:13 UTC, tyeth commented on generate_json_checksum.py
> +with open(sys.argv[1], 'r') as f:
Might be good to trap errors here (like no args and missing file), but looks like it's only for our usage anyway
```
C:\dev\arduino\Adafruit_Wippersnapper_Arduino [review-mode-sdlogger ≡ +1 ~1 -0 !]> python .\generate_json_checksum.py 
Traceback (most recent call last):
  File "C:\dev\arduino\Adafruit_Wippersnapper_Arduino\generate_json_checksum.py", line 6, in <module>
    with open(sys.argv[1], 'r') as f:
              ~~~~~~~~^^^
IndexError: list index out of range
C:\dev\arduino\Adafruit_Wippersnapper_Arduino [review-mode-sdlogger ≡ +1 ~1 -0 !]> python .\generate_json_checksum.py a.json
Traceback (most recent call last):
  File "C:\dev\arduino\Adafruit_Wippersnapper_Arduino\generate_json_checksum.py", line 6, in <module>
    with open(sys.argv[1], 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'a.json'
```

2025-01-09 18:25 UTC, tyeth commented on platformio.ini
> +extra_scripts = upload_no_build.py
Not intended to be here I believe

2025-01-09 18:29 UTC, tyeth commented on examples/config-file/offline-config.json
> +        "name": "DS18B20: Temperature Sensor (°F)",
This degree symbol is \u encoded in another config (src/config.json), not sure it matters, but was curious how the two ended up differing (were both from exports or one hand coded maybe)

2025-01-09 21:33 UTC, tyeth commented on src/components/analogIO/controller.cpp
> +    // TODO: Log out this data by calling a logging function in sdcard class
I'm assuming we're not doing general logging and only datapoints are logged to SD, is that correct?

2025-01-09 22:21 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS_V2.cpp
> +  FRESULT r = f_mkfs("", FM_FAT | FM_SFD, 0, workbuf_v2, sizeof(workbuf_v2));
This result could be checked too

2025-01-09 22:28 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS_V2.cpp
> +  if (!writeFSContents()) {
I don't think this should be called unless !is_fs_formatted so we avoid writing to the file system unnecessarily. Alternatively the comments throughout the method mention it being a fresh file system which won't be the case most of the time with the current code.
Alternatively the brownout PR can resolve that issue of unnecessarily replacing `bootout.txt` each boot and we can fix this up later.

2025-01-09 23:32 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.h
> +  4096 ///< Maximum length of the configuration JSON file, in Bytes
This will probably need to be bigger / doubled, the current offline-config is 1.5k with 4 components

2025-01-10 10:37 UTC, tyeth commented on src/Wippersnapper_V2.h
> +  char sUIDV2[13];        /*!< Unique network iface identifier */
dupe docstring, should be device not network iface (see [Wippersnapper_V2.cpp:L568](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/651f5275ef9ec1f467a30fc6c6f628fb68f659f9/src/Wippersnapper_V2.cpp#L568))

2025-01-10 10:43 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +bool ws_sdcard::ValidateChecksum(JsonDocument &doc) {
Docstring

2025-01-10 12:09 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +  doc["si_unit"] = SensorTypeToString(read_type);
Feels like this isn't the SI unit, but more the sensor type. Would this be translated to units when converting to spreadsheet?)

2025-01-10 12:14 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +  _sz_cur_log_file = szJson + 2; // +2 bytes for "\n"
Wouldn't it be +1 byte for \n

2025-01-10 12:16 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +            The GPIO pin number.
DS18b20 not GPIO sensor

2025-01-10 12:20 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.h
> +  bool _use_test_data;                 ///< True if sample data is being used for testing
This is never used

2025-01-10 12:40 UTC, tyeth commented on tests/diagram.json
> +    { "type": "board-ds18b20", "id": "temp1", "top": -87.53, "left": 272.88, "attrs": {} },
Might be helpful to set the different temps/ids per sensor, something like this for the attrs:
```
"attrs": {
      "deviceID": "010203040506",
      "familyCode": "16",
      "temperature": "-1",
      "minTemp": "-20",
      "maxTemp": "30",
      "tempWaveForm": "sine",
      "tempWaveFreq": "30"
    }
```

See here for details: https://github.com/bonnyr/wokwi-ds1820-custom-chip?tab=readme-ov-file#attributes

2025-01-10 13:04 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  WsV2._display->enableLogging();
appears to be a no-op

2025-01-10 13:07 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  check_valid_ssidV2(); // non-fs-backed, sets global credentials within network
This doesn't set the credentials, instead it scans for wifi networks and verifies the match against already existing network config

2025-01-10 13:33 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +      WS_DEBUG_PRINTLN("ERROR: Unable to decode BrokerToDevice message!");
useful to know which of the messages failed (i or i+1)

2025-01-10 13:36 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  WS_DEBUG_PRINT("IO Ban Error: ");
I was thinking about the device looking for known error strings (mqtt topic doesn't exist if component removed but device about to send periodic data) with it's device uuid in the message (if different uuid then ignore). If not known message then assume ban/backoff still. I think I need to test the ban situation from a second device to confirm what messages we may see.

2025-01-10 13:44 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  // Conversion to match integer UID sent by createMsgCheckinRequest()
What's the idea here, to drop leading zeros, or is there some potential translation error I'm missing?

2025-01-10 13:53 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  // Conversion to match integer UID sent by createMsgCheckinRequest()
Another thought just occurred to me, isn't it possible to have two boards with the same first 3 bytes of the mac address? Wouldn't that cause a big issue as the device ids are assumed to be unique?

2025-01-10 13:55 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +#ifdef USE_PSRAM
I kind of want to kill these off in favour of our own ws_malloc which does the same switch in one place

2025-01-10 14:05 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  WsV2.got_checkin_response = false;
I wondered about having this false be set after the publish, on line 1049, but not really much difference

2025-01-10 14:09 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +    WS_DEBUG_PRINTLN("Running in online mode...");
Curious about how you feel on this, purely around clarity. The else can be dropped and message moved down, but I was curious about whether you felt it clearer having the else. It could be, as in my mind it forces one to double check the conditional

2025-01-10 15:09 UTC, brentru commented on tests/diagrams/offline.json
> +        "attrs": { "color": "green" }
Yes, it should reflect `diagram.json` exactly.

Resolving..

2025-01-10 15:11 UTC, brentru commented on generate_json_checksum.py
> +with open(sys.argv[1], 'r') as f:
Trapping `FileNotFoundError`.

2025-01-10 15:12 UTC, brentru commented on upload_no_build.py
> +)
Not entirely sure why this artifact was still here, removed for now.

2025-01-10 15:17 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS_V2.cpp
> +  FRESULT r = f_mkfs("", FM_FAT | FM_SFD, 0, workbuf_v2, sizeof(workbuf_v2));
We are checking the `FRESULT` value returned by this function, `format_fs_fat12()` on L114:
```
  // If we are not formatted, attempt to format the filesystem as fat12
  if (!is_fs_formatted) {
    FRESULT rc = format_fs_fat12();

    if (rc != FR_OK) {
```

Is there something I'm missing here?

2025-01-10 15:18 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS_V2.cpp
> +  if (!writeFSContents()) {
This work started at the same time (or before) the brownout PR was submitted. We'll need to merge and include the brownout PR in API-V2 rather than rewriting this.

2025-01-10 15:21 UTC, brentru commented on src/provisioning/sdcard/ws_sdcard.h
> +  4096 ///< Maximum length of the configuration JSON file, in Bytes
Are you talking about `MAX_LEN_CFG_JSON`?

2025-01-10 15:22 UTC, brentru commented on src/Wippersnapper_V2.h
> +  char sUIDV2[13];        /*!< Unique network iface identifier */
Good catch!

2025-01-10 15:32 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +  WsV2._display->enableLogging();
The `display` ptr?

2025-01-10 15:33 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +  check_valid_ssidV2(); // non-fs-backed, sets global credentials within network
I think this may be out of scope for the sdlogger review as it's something I didn't touch for this PR.

2025-01-10 15:34 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +  // once this is returned, pb_dec_submessage()
Yeah, the controller handles instead of `pb_dec_submessage`

2025-01-10 15:35 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +      WS_DEBUG_PRINTLN("ERROR: Unable to decode BrokerToDevice message!");
Are you interested in logging which _specific_ message failed?

2025-01-10 15:35 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +  WS_DEBUG_PRINT("IO Ban Error: ");
This would be out of scope for this review as it was not touched as part of the offline mode work.

2025-01-10 15:36 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +  WsV2.got_checkin_response = false;
Marking this as out of scope

2025-01-10 15:38 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +    WS_DEBUG_PRINTLN("Running in online mode...");
Agreed, removed the `else` condition as the check within `if` `return`s.

2025-01-10 15:54 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.h
> +  4096 ///< Maximum length of the configuration JSON file, in Bytes
Yes 👍

2025-01-10 15:58 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +      WS_DEBUG_PRINTLN("ERROR: Unable to decode BrokerToDevice message!");
I guess not really in general, except once we have a bug report / issue, and at that point we can work out where it fell over.

2025-01-10 16:00 UTC, tyeth commented on src/Wippersnapper_V2.cpp
> +  WsV2._display->enableLogging();
not relevant to this PR, apologies, but yeah the enableLogging call has no method body content

2025-01-10 16:27 UTC, brentru commented on src/provisioning/sdcard/ws_sdcard.h
> +  4096 ///< Maximum length of the configuration JSON file, in Bytes
Increased that buffer size to `8192` bytes. In the grand scheme of things in WS and dynamically parsing a JSON file, it's not overkill

2025-01-10 16:28 UTC, brentru commented on tests/diagram.json
> +    { "type": "board-ds18b20", "id": "temp1", "top": -87.53, "left": 272.88, "attrs": {} },
Even if we're only using one DS18b20?

2025-01-10 16:29 UTC, brentru commented on src/Wippersnapper_V2.cpp
> +      WS_DEBUG_PRINTLN("ERROR: Unable to decode BrokerToDevice message!");
Here's what I think - this is the _high-level_ decoder method. If an error during decode occurs within the controller, the controller will log specific messages to the user.

2025-01-10 16:33 UTC, brentru commented on src/ws_manager.cpp
> +    ws_instance_v2 = new ws_adapter_wifi_v2();
I am confused here. What should L5:15 look like in `ws_manager.h`?

2025-01-10 16:36 UTC, tyeth commented on src/ws_manager.cpp
> +    ws_instance_v2 = new ws_adapter_wifi_v2();
```cpp
// For compiling with ESP32
#include "adapters/wifi/ws_wifi_esp32.h"
//typedef ws_wifi_esp32 ws_adapter_wifi;
#include "adapters/wifi/ws_wifi_esp32_v2.h"
//typedef ws_wifi_esp32_v2 ws_adapter_wifi_v2;

// Uncomment the following lines to compile for Pico
// NOTE: When compiling for pico, you must also modify L39-L40 to reflect the following lines
#include "adapters/offline/ws_offline_pico.h"
typedef ws_offline_pico ws_adapter_offline;
#include "adapters/offline/ws_offline_pico_v2.h"
typedef ws_offline_pico_v2 ws_adapter_offline_v2;
typedef ws_offline_pico ws_adapter_wifi;
typedef ws_offline_pico_v2 ws_adapter_wifi_v2;
```

2025-01-10 16:48 UTC, tyeth commented on src/ws_manager.cpp
> +    ws_instance_v2 = new ws_adapter_wifi_v2();
I should mention I added this at line 194 of boards.h as the default pico target in platformio.ini uses the non-w board:
```
#elif defined(ARDUINO_RASPBERRY_PI_PICO)
#define BOARD_ID "rpi-pico"
#define USE_TINYUSB
#define USE_STATUS_LED
#define STATUS_LED_PIN 32
#elif defined(ARDUINO_RASPBERRY_PI_PICO_2W)
#define BOARD_ID "rpi-pico-2w"
#define USE_TINYUSB
#define USE_STATUS_LED
#define STATUS_LED_PIN LED_BUILTIN
```

2025-01-10 17:00 UTC, brentru commented on src/ws_manager.cpp
> +    ws_instance_v2 = new ws_adapter_wifi_v2();
Got it! Thanks for clarifying.

2025-01-10 17:01 UTC, brentru commented on src/provisioning/sdcard/ws_sdcard.h
> +  bool _use_test_data;                 ///< True if sample data is being used for testing
This has been removed in favor of streaming test data over the serial in debug mode.

2025-01-10 17:25 UTC, tyeth commented on tests/diagram.json
> +    { "type": "board-ds18b20", "id": "temp1", "top": -87.53, "left": 272.88, "attrs": {} },
I think I saw an error/warning logged about having 0 as the serial number, but not fatal. Wouldn't worry too much about it, although having moving data points also seemed useful (but think we talked in the past and said constant)

2025-01-10 17:27 UTC, brentru commented on src/provisioning/sdcard/ws_sdcard.cpp
> +  doc["si_unit"] = SensorTypeToString(read_type);
Totally, I'm refactoring that in the next commit! Great catch.

2025-01-10 17:28 UTC, tyeth commented on src/provisioning/tinyusb/Wippersnapper_FS_V2.cpp
> +  FRESULT r = f_mkfs("", FM_FAT | FM_SFD, 0, workbuf_v2, sizeof(workbuf_v2));
Yeah sorry I should be clearer. Line 71 gets the result of f_mkfs into r, then like 75 overwrites that result with the mount attempt, then we check r. I'd expect to check for failure before the mount too (same end result probably not worth changing)

2025-01-10 20:42 UTC, brentru commented on src/provisioning/tinyusb/Wippersnapper_FS_V2.cpp
> +  FRESULT r = f_mkfs("", FM_FAT | FM_SFD, 0, workbuf_v2, sizeof(workbuf_v2));
Got it! Changed the logic to return r if `FR_OK` is not ret'd on that line, also modified L88 to perform a similar check since it's setting `r` but not returning until the function ends.

2025-01-10 20:44 UTC, brentru commented on examples/config-file/offline-config.json
> +        "name": "DS18B20: Temperature Sensor (°F)",
> This degree symbol is \u encoded in another config (src/config.json)

Removed it, that was a duplicate file.

> Also the sensor component appears to be including two metrics, so should be named differently, and presumably major rework for the front end / rails to accommodate (but totally in line with our talk of one poll period per sensor instead of subcomponent).

Could you please clarify this point - not sure I follow

2025-01-10 20:52 UTC, tyeth commented on examples/config-file/offline-config.json
> +        "name": "DS18B20: Temperature Sensor (°F)",
Ignore that last one about the two metrics for the ds18b20 in config, but I was alluding to the fact the "name" mentioned *F but was actually for *C and *F (two metrics), and that we don't have an example config structure for that yet (so was unfamiliar with sensor_count etc) nor frontend support (both expected)

2025-01-10 21:28 UTC, tyeth commented on examples/config-file/offline-config.json
> +        "name": "DS18B20: Temperature Sensor (°F)",
To clarify it's just that the name of that component object is for both of the two subcomponents (°C and °F), so I guess we drop the fahrenheit from the name field, and the web front end will already give them units.

2025-01-13 17:11 UTC, brentru commented
@tyeth  Please give this a re-review. I have changed what we discussed. I'm going to merge this branch into the api-v2 branch after you give the OK.

2025-01-14 18:35 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +    return "";
This looks like it's missing

2025-01-14 18:38 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +    return "m/s/s";
feels like this should match gravity/linear-acceleration, but happy to not have it match if preferred

2025-01-14 18:42 UTC, tyeth requested changes
Minor changed in units method, the ambient fahrenheit specifically, maybe accelerometer too.

2025-01-14 18:42 UTC, tyeth commented on src/provisioning/sdcard/ws_sdcard.cpp
> +    return "raw value";
I wonder about leaving this blank, but having an empty field might be more frustrating for people

2025-02-11 20:13 UTC, brentru commented
Merged into migrate-api-v2. Thank you for the review!

2025-02-11 20:13 UTC, closed without merging